library/bigip_device_dns.py
library/bigip_ucs_fetch.py
library/bigip_user.py

Hey there,
some of your modules had broken DOCSTRINGs which didn't work with `ansible-doc`. I fixed it with this PR :)

Fixed DOCSTRINGs

---

library/bigip_virtual_server.py

This patch enables route advertisement for virtual server's ip.

enable route advertisement

---

library/bigip_selfip.py
roles/__bigip_selfip/defaults/main.yaml
roles/__bigip_selfip/tasks/main.yaml

I have enabled the optional functionality of creating self IP for a specific route domain. Please review and consider approving the pull request.
- Manu
Example:
name: Create Self IP with a Route Domain bigip_selfip: server: "lb.mydomain.com" user: "admin" password: "secret" validate_certs: "no" name: "self1" address: "10.10.10.10" netmask: "255.255.255.0" vlan: "vlan1" rd: "10" allow_service: "default" delegate_to: localhost

Adding rd Functionality

---

inventory/group_vars/all
library/bigip_user.py
roles/bigip_user/tasks/main.yaml
roles/bigip_user/tasks/test-post-version-12-specific.yaml
test/bigip/test_bigip_user.py

Problem:
bigip_user lib needed an overhaul to be usable, this has led to quite a few issues
Analysis:
Reworked bigip_user lib with the corresponding tests and docs, to be in line with the new convention. Added few safety checks to ensure that existing data does not get overwritten.
Tests:
Unit
Functional
Flake 8

Fixes #29 #85

---

library/bigip_device_ntp.py
test/integration/bigip_device_ntp.yaml
test/unit/bigip/fixtures/load_ntp.json
test/unit/bigip/test_bigip_device_ntp.py

Problem:
bigip_device_ntp was using v2 conventions
Analysis:
Amended bigip_device_ntp to use v3 conventions
Tests:
Unit
Functional

Fixes #150

---

library/bigip_selfip.py

I'm not sure I did this right, but this is in response to https://github.com/F5Networks/f5-ansible/issues/250

adding validation to the IP address param and compressing for IPv6 checking

---

library/bigip_iapp_service.py
test/integration/targets/bigip_iapp_service/files/appsvcs_integration_v2.0.004.tmpl
test/integration/targets/bigip_iapp_service/files/f5-http-url-routing-lb.parameters.json
test/integration/targets/bigip_iapp_service/tasks/issue-00263.yaml
test/integration/targets/bigip_iapp_service/tasks/main.yaml
test/unit/bigip/fixtures/create_iapp_service_parameters_f5_http.json
test/unit/bigip/test_bigip_iapp_service.py

Added missing fileds for REST call.

---

library/bigip_software_facts.py
test/integration/bigip_software_facts.yaml
test/integration/targets/bigip_software_facts/defaults/main.yaml
test/integration/targets/bigip_software_facts/tasks/main.yaml
test/unit/bigip/test_bigip_software_facts.py

Problem:
New module for fetching bigip software facts was required
Analysis:
New module to gather volumes, images and hotfix information has been
added
Tests:
Unit
Functional

Fixes #293

---

library/bigip_software.py

changed variable name as per #312

fixes incorrect variable name as per issue #312

---

docs/_templates/layout.html

This should fix the issue where the build breaks in RTD because it can't find f5-sphinx-theme/header.html.

implementation for f5-sphinx-theme

---

test/unit/bigip/test_bigip_command.py

…and updating previous unit test to ensure cli was not called.

Adding unit test to cover cli transport

---

examples/0000-getting-started/playbook.yaml
examples/0000-getting-started/undo-playbook.yaml

the undo example is not the most well thought out, the typo is a current issue.

fix typo;add undo example

---

docs/make.bat
docs/usage/getting_started.rst
docs/usage/installing-modules.rst
docs/usage/virtualenv.rst

A customer was trying to install Ansible on their Mac and failing.  These changes are an attempt to provide a sane starting point for someone to use F5 Ansible and knows nothing about either Ansible and/or Python.
Some of this content "borrowed" from @mcgonagle https://github.com/mcgonagle/ansible_f5/blob/master/docs/INSTALL.md

add virtualenv; soften not using pip; example of using bleeding-edge

---

docs/usage/getting_started.rst

Added note about modules not being supported

added note that F5 modules are not supported

---

library/bigip_device_connectivity.py

this seemed to me like the best way to handle the management-ip thing - just embrace it and allow "management-ip" to be specified in the play.  That gives you the green "ok" every time, without it you'll always get notified that it was changed when it wasn't.
Note that this does not work on 11.6.x because pre-12.0.0 didn't convert the management IP address to the keyword "management-ip", but specifying the actual management IP address in the play does work on all versions.

Fixes #412

---

.travis.yml
Makefile
docs/scripts/test-docs.sh

- Add docs test script to travis scripts section.
- Add docs deployment to makefile; add make command for deployment to travis.

docs build, testing, and deployment

---

docs/usage/connection-local-or-delegate-to.rst
docs/usage/filing-issues.rst
docs/usage/getting_started.rst
docs/usage/installing-modules.rst
docs/usage/requirements.rst
docs/usage/virtualenv.rst

Editing one doc directory at a time; usage dir mostly done now.

edited docs in usage dir to clean up passive and other build issues

---

test/integration/iworkflow_system_setup.yaml
test/integration/iworkflow_tenant.yaml
test/integration/iworkflow_tenant_connector.yaml
test/integration/iworkflow_user.yaml
test/integration/targets/iworkflow_system_setup/tasks/main.yaml
test/integration/targets/iworkflow_tenant/tasks/main.yaml
test/integration/targets/iworkflow_tenant_connector/tasks/main.yaml

iworkflow_tenant, iworkflow_tenant_connector, and iworkflow_user modules.
- 2-space indenting
- replacing 'with_items:' with 'loop:'

Standards and formatting for integration tests of iworkflow_system_setup,

---

test/integration/targets/bigip_profile_client_ssl/tasks/test-cert-key-chain.yaml

Fixed the check and then decided to add some more test steps but the new test steps seem to reveal a new issue.

Bad idempotent check in a bigip_profile_client_ssl test.

---

test/integration/targets/bigip_gtm_server/tasks/issue-00513.yaml
test/integration/targets/bigip_gtm_server/tasks/main.yaml
test/integration/targets/bigip_gtm_server/vars/issue-00513.yaml

Try to change link_discovery and virtual_server_discovery in bigip_gtm_server after the server has been created.

Tests corresponding to issue 513

---

docs/index.rst
docs/usage/getting_started.rst
docs/usage/installing-modules.rst
docs/usage/support.rst

Updated support details and reorganized related information

updated support details

---

docs/usage/virtualenv.rst

minor edits for issue 575

---

examples/0006-using-rest-api-directly/README.rst
examples/0006-using-rest-api-directly/playbook.yaml
examples/0006-using-rest-api-directly/undo-playbook.yaml

fake idempotency
delete auth token

0006 fake idempotency

---

examples/0006-using-rest-api-directly/playbook-with-transaction.yaml
examples/0006-using-rest-api-directly/playbook.yaml
examples/0006-using-rest-api-directly/undo-playbook-with-transaction.yaml
examples/0006-using-rest-api-directly/undo-playbook.yaml

- add save config 
- new example of using transaction

examples/0006-using-rest-api-directly: save config / transactions

---

docs/index.rst
docs/usage/support.rst
docs/usage/supported-versions.rst

Pulled out support details and put into their own section

pulled out big-ip versions

---

docs/usage/guide_f5.rst

Draft content for Ansible scenarios guide

f5 guide draft

---

docs/usage/support.rst

Need to provide link so new users can sign up if they don't have account.

updated slack link

---

docs/usage/getting_started.rst
docs/usage/playbook_tutorial.rst

There is also an issue with the css that is pushing the table of contents to the left/cutting it off. This should hopefully fix.

removed quotes from yaml, removed deepdiff from prereqs

---

SUPPORT.rst

Updating SUPPORT file to reflect F5 policies for open source project as per AskF5 article [SOL80012344](https://support.f5.com/kb/en-us/solutions/public/k/80/sol80012344.html).

Updating support policy to refer to AskF5 KB and F5 policies.

---

docs/usage/supported-versions.rst

Documentation
```
v2.5.0
```
First draft update to list supported releases and BIG-IP and BIG-IQ supported versions.

Updated releases and version page to include supported matrix.

---

README.rst
docs/usage/getting_started.rst
docs/usage/support.rst
docs/usage/supported-versions.rst

Updated language in multiple places, now that it's supported...

changed language to supported

---

library/modules/bigip_monitor_tcp.py
test/integration/targets/bigip_monitor_tcp/tasks/issue-00838.yaml
test/integration/targets/bigip_monitor_tcp/tasks/main.yaml
test/integration/targets/bigip_monitor_tcp/vars/issue-00838.yaml

Adding tests, fixes issue #838

Adding description parameter in the bigip_monitor_http module

---

library/modules/bigip_monitor_https.py
test/integration/targets/bigip_monitor_https/tasks/issue-00835.yaml
test/integration/targets/bigip_monitor_https/tasks/main.yaml
test/integration/targets/bigip_monitor_https/vars/issue-00835.yaml

Adding tests, fixes issue #835

Adding description parameter in the bigip_monitor_https module

---

library/module_utils/network/f5/common.py
library/modules/bigip_profile_client_ssl.py
test/integration/targets/bigip_profile_client_ssl/tasks/issue-00846.yaml
test/integration/targets/bigip_profile_client_ssl/vars/issue-00846.yaml

Fixes #873

---

library/modules/bigip_static_route.py
test/integration/targets/bigip_static_route/defaults/main.yaml
test/integration/targets/bigip_static_route/tasks/issue-00104.yaml
test/integration/targets/bigip_static_route/tasks/issue-00752.yaml
test/integration/targets/bigip_static_route/tasks/issue-00865.yaml
test/integration/targets/bigip_static_route/tasks/main.yaml
test/integration/targets/bigip_static_route/tasks/setup.yaml
test/integration/targets/bigip_static_route/tasks/teardown.yaml
test/integration/targets/bigip_static_route/vars/issue-00865.yaml

fixes #865, #884

---

library/modules/bigip_monitor_dns.py
library/modules/bigip_monitor_tcp_echo.py

- adding helper function set_default_creation_values()
- removing SDK, converting classes to reflect current standards,
- moving client definition outside of try/except block as in some edge cases this would cause assignment errors

removed SDK from bigip_monitor_tcp_echo, converted classes to reflect current standards

---

library/modules/bigip_monitor_https.py

removed SDK, converted classes to reflect current standards

removed SDK from bigip_monitor_https, converted classes to reflect current standards

---

library/modules/bigip_monitor_http.py

removed SDK, converted classes to reflect current standards

removed SDK from bigip_monitor_http, converted classes to reflect current standards

---

library/modules/bigip_monitor_external.py

- removing SDK, converting classes to reflect current standards
- correcting 'parent' property

remove_sdk_monitor_external

---

library/modules/bigip_monitor_tcp.py
library/modules/bigip_monitor_udp.py

- removing SDK, converting classes to reflect current standards
- removing redundant function in bigip_monitor_tcp module
- correcting 'parent' property
- adding helper function set_default_creation_values()

remove_sdk_bigp_monitor_udp

---

library/modules/bigip_profile_client_ssl.py
test/integration/targets/bigip_profile_client_ssl/tasks/issue-00398.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/issue-00532.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/issue-00739.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/main.yaml

I will add commits here so do not merge yet until I will say its done

fixes #910

---

library/modules/bigip_pool_member.py
test/integration/targets/bigip_pool_member/tasks/provider/issue-00743.yaml

removing SDK dependency from module
adding cleanup to provider tests

SDK dependency removal bigip_pool_member module

---

library/modules/bigip_pool.py

adding a workaround to bug in monitor string

removing SDK from bigip_pool module

---

library/module_utils/network/f5/icontrol.py
library/modules/bigip_gtm_server.py

adding tmos version check method to iControl
adding provision check method to iControl

removing SDK from bigip_gtm_server

---

library/modules/bigip_gtm_server.py
test/integration/targets/bigip_gtm_server/tasks/issue-00772.yaml
test/integration/targets/bigip_gtm_server/tasks/main.yaml
test/integration/targets/bigip_gtm_server/vars/issue-00772.yaml

adding monitors to gtm servers

fixes #772

---

library/modules/bigip_device_dns.py
test/integration/targets/bigip_device_dns/tasks/main.yaml

- reworking module to fit current class system
- removing redundant parameters
- removing SDK from module
I had to rework most of the items and removed stuff that was unnecessary or seemed unfinished. All tests pass.

refactor of bigip_device_dns module

---

library/modules/bigip_device_dns.py

refactoring absent method and merging functionality into Diff class

---

library/modules/bigip_device_ntp.py

- refactoring module to fit current class system
- removing SDK from module

refactor of bigip_ntp_device module

---

library/modules/bigip_device_sshd.py
test/integration/targets/bigip_device_sshd/tasks/main.yaml
test/integration/targets/bigip_device_sshd/tasks/setup.yaml

refactoring bigip_device_sshd module to current standards
removing SDK

refactoring bigip_device_sshd module

---

library/modules/bigip_device_group.py
library/modules/bigip_device_group_member.py

adding partition parameter
removing SDK

refactor of bigip_device_group_member module

---

library/modules/bigip_data_group.py
test/integration/targets/bigip_data_group/tasks/issue-00652.yaml
test/integration/targets/bigip_data_group/tasks/main.yaml

removing sdk from bigip_data_group

---

library/modules/bigip_partition.py

refactoring to current class system

remove SDK from bigip_partition module

---

library/modules/bigip_device_license.py

I need to get the license test file we use for those tests, unless you can test this on your machine @caphrim007

removing SDK from module bigip_device_license

---

library/modules/bigip_configsync_action.py

- removing SDK from module
- refactoring to be in line with current class system
I will improve the test for this in a later PR

removing sdk from config_sync_action

---

library/module_utils/network/f5/common.py
library/modules/bigip_sys_global.py
test/integration/targets/bigip_sys_global/defaults/main.yaml
test/integration/targets/bigip_sys_global/tasks/main.yaml

correcting docs
removing deprecation warning

refactor of bigip_sys_global

---

library/modules/bigip_remote_syslog.py

refactoring to current class system

removing SDK from bigip_remote_syslog

---

library/modules/bigip_ucs.py

this needs local testing as my connection times out due to file/sizes @caphrim007

removing SDK from module from bigip_ucs

---

library/module_utils/network/f5/bigip.py
library/modules/bigip_sys_db.py
library/modules/bigip_sys_global.py

refactoring to current class system

removing SDK from module

---

library/module_utils/network/f5/common.py
library/modules/bigip_policy_rule.py

removing SDK from bigip_policy_rule

---

library/module_utils/network/f5/urls.py
library/modules/bigip_iapp_service.py
test/integration/targets/bigip_iapp_service/tasks/issue-00089.yaml
test/integration/targets/bigip_iapp_service/tasks/issue-00137.yaml
test/integration/targets/bigip_iapp_service/tasks/issue-00138.yaml
test/integration/targets/bigip_iapp_service/tasks/issue-00254.yaml
test/integration/targets/bigip_iapp_service/tasks/issue-00263.yaml
test/integration/targets/bigip_iapp_service/tasks/main.yaml

removing SDK from iapp_service module

---

library/module_utils/network/f5/urls.py
library/modules/bigip_device_facts.py
library/modules/bigip_vcmp_guest.py
test/integration/targets/bigip_vcmp_guest/tasks/setup.yaml

removing SDK from vcmp_guest module

---

library/module_utils/network/f5/icontrol.py
library/modules/bigip_provision.py
test/integration/targets/bigip_provision/tasks/issue-00663.yaml
test/integration/targets/bigip_provision/tasks/issue-00669.yaml

add TransactionContextManager
remove SDK from bigip provision

fixes #755

---

library/modules/bigip_profile_http.py
library/modules/bigip_routedomain.py
test/integration/targets/bigip_routedomain/tasks/issue-01036.yaml
test/integration/targets/bigip_routedomain/tasks/main.yaml
test/integration/targets/bigip_routedomain/vars/issue-01036.yaml

fixes_1036

---

library/modules/bigip_selfip.py
test/integration/targets/bigip_selfip/tasks/args/issue-01038.yaml
test/integration/targets/bigip_selfip/tasks/args/main.yaml
test/integration/targets/bigip_selfip/tasks/environment/issue-01038.yaml
test/integration/targets/bigip_selfip/tasks/environment/main.yaml
test/integration/targets/bigip_selfip/tasks/provider/issue-01038.yaml
test/integration/targets/bigip_selfip/tasks/provider/main.yaml

fixes_1038

---

library/modules/bigip_ike_peer.py
test/integration/targets/bigip_ike_peer/tasks/issue-01035.yaml
test/integration/targets/bigip_ike_peer/tasks/main.yaml
test/integration/targets/bigip_ike_peer/vars/issue-01035.yaml

fixes_1035

---

library/modules/bigip_traffic_selector.py
test/integration/targets/bigip_traffic_selector/tasks/issue-01034.yaml
test/integration/targets/bigip_traffic_selector/tasks/main.yaml
test/integration/targets/bigip_traffic_selector/vars/issue-01034.yaml

fixes_1034

---

library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01040.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml

Fixes 1040

---

library/modules/bigip_partition.py
test/integration/targets/bigip_partition/tasks/issue-01052.yaml
test/integration/targets/bigip_partition/tasks/main.yaml

fixes #1052

---

library/modules/bigip_pool_member.py
test/integration/targets/bigip_pool_member/tasks/provider/issue-00887.yaml
test/integration/targets/bigip_pool_member/tasks/provider/main.yaml

fixes #887

---

library/module_utils/network/f5/ipaddress.py
library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-00650.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml

fixes #650

---

library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-00650.yaml

fixes #1058

---

devtools/stubs/library_module.py

- change the module template to reflect removal of SDK
- reorder of functions so that all on device operations are in sequence one after another, for ease of code analysis
- change author details to be more generic

fixes_1069

---

library/modules/bigip_asm_policy_fetch.py
library/modules/bigip_profile_analytics.py
test/integration/bigip_asm_policy_fetch.yaml
test/integration/targets/bigip_asm_policy_fetch/defaults/main.yaml
test/integration/targets/bigip_asm_policy_fetch/tasks/main.yaml
test/integration/targets/bigip_asm_policy_fetch/tasks/setup.yaml
test/integration/targets/bigip_asm_policy_fetch/tasks/teardown.yaml
test/units/modules/network/f5/test_bigip_asm_policy_fetch.py

Adding ASM policy export module (issue 280)

---

library/plugins/lookup/bigiq_license.py

this is for review, not tested yet, need to discuss how to do this, but most importantly review of code, also docs need adding
@caphrim007

Adding bigiq lookup

---

library/modules/bigip_asm_policy_manage.py
library/modules/bigip_wait.py
library/plugins/lookup/bigiq_license.py
test/integration/bigip_asm_policy_manage.yaml
test/integration/targets/bigip_asm_policy_manage/defaults/main.yaml
test/integration/targets/bigip_asm_policy_manage/files/v1_policy_default_compact_format_enabled.xml
test/integration/targets/bigip_asm_policy_manage/tasks/main.yaml
test/integration/targets/bigip_asm_policy_manage/tasks/setup.yaml
test/integration/targets/bigip_asm_policy_manage/tasks/teardown.yaml
test/units/modules/network/f5/test_bigip_asm_policy_manage.py

fixes #1093

---

library/modules/bigip_asm_policy.py

fixes #1096

---

library/modules/bigip_asm_policy_fetch.py
library/modules/bigip_asm_policy_import.py
library/modules/bigip_asm_policy_manage.py
library/modules/bigip_asm_policy_server_technology.py
test/integration/targets/bigip_asm_policy_fetch/tasks/setup.yaml
test/integration/targets/bigip_asm_policy_fetch/tasks/teardown.yaml
test/integration/targets/bigip_asm_policy_manage/tasks/main.yaml

Fixes odata filter

---

library/modules/bigip_pool_member.py
test/integration/targets/bigip_pool_member/tasks/provider/issue-01108.yaml
test/integration/targets/bigip_pool_member/tasks/provider/main.yaml

fixes 1108

---

library/modules/bigip_device_facts.py
test/integration/targets/bigip_device_facts/tasks/issue-01095.yaml
test/integration/targets/bigip_device_facts/tasks/main.yaml

fixes #1095

---

library/plugins/action/bigip_imish_config.py

backport ansible core changes

---

library/modules/bigip_apm_policy_fetch.py
library/modules/bigip_apm_policy_import.py
library/modules/bigip_asm_policy_fetch.py
library/modules/bigip_asm_policy_import.py

change return value types to upstream

change return value types

---

docs/modules/bigip_apm_policy_fetch_module.rst
docs/modules/bigip_asm_policy_fetch_module.rst
docs/modules/bigip_asm_policy_import_module.rst
docs/modules/bigip_asm_policy_manage_module.rst
docs/modules/bigip_asm_policy_server_technology_module.rst
docs/modules/bigip_asm_policy_signature_set_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_apm_policy_import.py
library/modules/bigip_asm_policy_signature_set.py

upstreaming fix

---

library/plugins/action/bigip.py

workaround to import issue preventing f5ansible galaxy role usage

import workaround

---

.travis.yml
requirements.shippable.txt
shippable.yml
tox.ini

added shippable as secondary test source
tox cleanup
travis settings cleanup

enchancing automated tests

---

.travis.yml
README.rst
requirements.travis.txt

updated readme badges

---

library/modules/bigip_gtm_pool_member.py
library/modules/bigip_gtm_virtual_server.py
library/modules/bigip_pool.py
library/modules/bigip_pool_member.py
test/integration/targets/bigip_gtm_pool_member/tasks/issue-00716.yaml
test/integration/targets/bigip_gtm_pool_member/tasks/issue-00790.yaml
test/integration/targets/bigip_gtm_pool_member/tasks/issue-01153.yaml
test/integration/targets/bigip_gtm_pool_member/tasks/issue-01185.yaml
test/integration/targets/bigip_gtm_pool_member/tasks/main.yaml
test/integration/targets/bigip_gtm_pool_member/tasks/teardown.yaml
test/integration/targets/bigip_gtm_virtual_server/tasks/issue-00718.yaml
test/integration/targets/bigip_gtm_virtual_server/tasks/issue-01186.yaml
test/integration/targets/bigip_gtm_virtual_server/tasks/main.yaml
test/integration/targets/bigip_gtm_virtual_server/tasks/teardown.yaml
test/integration/targets/bigip_pool_member/tasks/provider/issue-00881.yaml
test/integration/targets/bigip_pool_member/tasks/provider/issue-01027.yaml
test/integration/targets/bigip_pool_member/tasks/provider/issue-01108.yaml
test/units/modules/network/f5/test_bigip_gtm_pool_member.py
test/units/modules/network/f5/test_bigip_pool.py
test/units/modules/network/f5/test_bigip_pool_member.py

- minor fixes to bigip_pool and bigip_pool_member modules aggregates
- fixed #1186
- implemented proper fix for #1153 to be in line with current conventions set by bigip_pool module
- added gtm pool aggregates #1185

multiple_fixes

---

.github/ISSUE_TEMPLATE.md
docs/usage/filing-issues.rst

added filing issue requirements

added filing issue requirements

---

library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01187.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml
test/integration/targets/bigip_virtual_server/vars/issue-01187.yaml

fixes #1187

---

library/modules/bigip_gtm_pool_member.py
library/modules/bigip_pool.py
library/modules/bigip_pool_member.py
library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01163.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml
test/integration/targets/bigip_virtual_server/vars/issue-01163.yaml

fixes #1163

---

library/module_utils/network/f5/icontrol.py
library/modules/bigiq_application_fasthttp.py
library/modules/bigiq_application_fastl4_tcp.py
library/modules/bigiq_application_fastl4_udp.py
library/modules/bigiq_application_http.py
library/modules/bigiq_application_https_offload.py
library/modules/bigiq_application_https_waf.py
test/units/modules/network/f5/test_bigiq_application_fasthttp.py
test/units/modules/network/f5/test_bigiq_application_fastl4_tcp.py
test/units/modules/network/f5/test_bigiq_application_fastl4_udp.py
test/units/modules/network/f5/test_bigiq_application_http.py
test/units/modules/network/f5/test_bigiq_application_https_offload.py
test/units/modules/network/f5/test_bigiq_application_https_waf.py

fixes #1198

---

library/modules/bigip_profile_persistence_cookie.py
test/integration/targets/bigip_profile_persistence_cookie/tasks/provider/issue-01164.yaml
test/integration/targets/bigip_profile_persistence_cookie/tasks/provider/main.yaml

fixes #1164

---

library/modules/bigip_iapplx_package.py

fixes #1192

---

library/modules/bigip_profile_client_ssl.py
test/integration/targets/bigip_profile_client_ssl/tasks/issue-01201.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/main.yaml

fixes #1201

---

library/modules/bigiq_device_discovery.py
test/integration/bigiq_device_discovery.yaml
test/integration/targets/bigiq_device_discovery/defaults/main.yaml
test/integration/targets/bigiq_device_discovery/tasks/main.yaml
test/units/modules/network/f5/fixtures/load_machine_resolver.json
test/units/modules/network/f5/test_bigiq_device_discovery.py

fixes #994

---

library/modules/bigip_device_facts.py
test/integration/targets/bigip_device_facts/tasks/issue-01159.yaml

fixes #1159

---

devtools/stubs/library_module.py
tasks/module_doc_fragments.py

update stubber templates

---

library/modules/bigip_data_group.py
test/integration/targets/bigip_data_group/tasks/issue-01210.yaml
test/integration/targets/bigip_data_group/tasks/main.yaml
test/units/modules/network/f5/test_bigip_data_group.py

Fixes #1210
Also addresses changes required in: #1230, #1226

bigip_data_group bug fix

---

library/modules/bigip_data_group.py

fixes #1128

---

library/utils/module_docs_fragments/f5.py

fixes automatic docs building

---

library/modules/bigiq_device_discovery.py
test/integration/targets/bigiq_device_discovery/defaults/main.yaml
test/integration/targets/bigiq_device_discovery/tasks/issue-01241.yaml
test/integration/targets/bigiq_device_discovery/tasks/issue-01242.yaml
test/integration/targets/bigiq_device_discovery/tasks/issue-01243.yaml
test/integration/targets/bigiq_device_discovery/tasks/main.yaml
test/integration/targets/bigiq_device_discovery/vars/issue-01241.yaml
test/integration/targets/bigiq_device_discovery/vars/issue-01242.yaml
test/integration/targets/bigiq_device_discovery/vars/issue-01243.yaml

fixes #1241, fixes #1242, fixes #1243

bigiq_device_discovery improvements

---

docs/modules/bigip_data_group_module.rst
library/modules/bigip_data_group.py
library/modules/bigip_gtm_pool_member.py

Backports and fixes

---

library/modules/bigip_data_group.py
library/modules/bigip_device_auth_ldap.py
library/modules/bigip_device_connectivity.py
library/modules/bigip_gtm_pool.py
library/modules/bigip_gtm_server.py
library/modules/bigip_gtm_virtual_server.py
library/modules/bigip_lx_package.py
library/modules/bigip_pool_member.py
library/modules/bigip_routedomain.py
library/modules/bigip_ssl_ocsp.py
library/modules/bigip_ucs_fetch.py
library/modules/bigiq_application_https_offload.py
library/modules/bigiq_application_https_waf.py
library/modules/bigiq_device_discovery.py
library/modules/bigiq_device_facts.py
test/units/modules/network/f5/test_bigip_lx_package.py
test/units/modules/network/f5/test_bigip_monitor_tcp_half_open.py
test/units/modules/network/f5/test_bigip_monitor_udp.py
test/units/modules/network/f5/test_bigiq_device_discovery.py

upstream fixes

---

library/modules/bigip_gtm_pool.py
library/modules/bigip_gtm_wide_ip.py
test/units/modules/network/f5/test_bigip_gtm_pool.py
test/units/modules/network/f5/test_bigip_gtm_wide_ip.py

deprecates v11 legacy support for GTM modules

deprecates v11 support for GTM modules

---

library/modules/bigip_vcmp_guest.py
test/integration/targets/bigip_vcmp_guest/tasks/issue-01276.yaml
test/integration/targets/bigip_vcmp_guest/tasks/main.yaml
test/integration/targets/bigip_vcmp_guest/vars/issue-01276.yaml
test/units/modules/network/f5/test_bigip_vcmp_guest.py

I could not find a good way to write tests for it but I did test it with our setup and seems to be working fine.

added initial_hotfix parameter for bigip_vcmp_guest.py

---

docs/modules/bigip_firewall_log_profile_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_firewall_log_profile.py
library/modules/bigip_remote_syslog.py
test/integration/bigip_firewall_log_profile.yaml
test/integration/targets/bigip_firewall_log_profile/defaults/main.yaml
test/integration/targets/bigip_firewall_log_profile/tasks/main.yaml
test/integration/targets/bigip_firewall_log_profile/tasks/setup.yaml
test/integration/targets/bigip_firewall_log_profile/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_afm_log_global_network_profile.json
test/units/modules/network/f5/test_bigip_firewall_log_profile.py

Feature.add afm log profile

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/main.yaml

fixes #1320

---

docs/modules/bigip_firewall_log_profile_module.rst
docs/modules/bigip_firewall_log_profile_network_module.rst
docs/modules/bigip_vcmp_guest_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_firewall_log_profile.py
library/modules/bigip_firewall_log_profile_network.py
test/integration/bigip_firewall_log_profile_network.yaml
test/integration/targets/bigip_firewall_log_profile/tasks/main.yaml
test/integration/targets/bigip_firewall_log_profile_network/defaults/main.yaml
test/integration/targets/bigip_firewall_log_profile_network/tasks/main.yaml
test/integration/targets/bigip_firewall_log_profile_network/tasks/setup.yaml
test/integration/targets/bigip_firewall_log_profile_network/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_afm_global_network_log_network.json
test/units/modules/network/f5/test_bigip_firewall_log_profile.py
test/units/modules/network/f5/test_bigip_firewall_log_profile_network.py

adds module to manipulate network log settings on AFM log profile

fixes #1316

---

docs/modules/bigip_firewall_rule_module.rst
library/modules/bigip_firewall_rule.py
test/integration/targets/bigip_firewall_rule/tasks/issue-01314.yaml
test/integration/targets/bigip_firewall_rule/tasks/main.yaml
test/integration/targets/bigip_firewall_rule/vars/issue-01314.yaml

fixes #1314

---

docs/modules/bigip_remote_user_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_firewall_schedule.py
library/modules/bigip_remote_user.py
test/integration/bigip_remote_user.yaml
test/integration/targets/bigip_remote_user/defaults/main.yaml
test/integration/targets/bigip_remote_user/tasks/main.yaml
test/integration/targets/bigip_remote_user/tasks/setup.yaml
test/integration/targets/bigip_remote_user/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_remote_user_settings.json
test/units/modules/network/f5/test_bigip_remote_user.py

New_Module: bigip_remote_user

---

docs/modules/bigip_device_facts_module.rst
library/modules/bigip_device_facts.py
test/integration/targets/bigip_device_facts/tasks/issue-01159.yaml
test/units/modules/network/f5/test_bigip_device_facts.py

fixes #1321

---

docs/conf.py
requirements.readthedocs.txt
requirements.shippable.txt
requirements.travis.txt

These changes will get the theme updated to the version it should be. Also, added sphinx-copybutton, which is a little copy button that shows up for code blocks.

updated theme, sphinx version, copyright, and button

---

library/modules/bigip_device_facts.py

fixes docs

---

docs/modules/bigip_profile_tcp_module.rst
library/modules/bigip_profile_tcp.py
test/integration/targets/bigip_profile_tcp/tasks/issue-01309.yaml
test/integration/targets/bigip_profile_tcp/tasks/main.yaml
test/integration/targets/bigip_profile_tcp/vars/issue-01309.yaml

adds new parameters to tcp profile module

---

library/modules/_bigip_device_facts.py
library/modules/_bigiq_device_facts.py
library/modules/bigip_device_info.py
library/modules/bigip_selfip.py
library/modules/bigiq_device_info.py
test/units/modules/network/f5/test_bigip_device_info.py
test/units/modules/network/f5/test_bigiq_device_info.py

changes in the Ansible core to facts module naming
corrected check mode in selfip

changes in the upstream

---

docs/modules/bigip_device_info_module.rst
docs/modules/bigip_message_routing_peer_module.rst
docs/modules/bigiq_device_info_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_message_routing_route.py
test/integration/bigip_message_routing_route.yaml
test/integration/targets/bigip_message_routing_route/defaults/main.yaml
test/integration/targets/bigip_message_routing_route/tasks/main.yaml
test/integration/targets/bigip_message_routing_route/tasks/setup.yaml
test/integration/targets/bigip_message_routing_route/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_generic_route.json
test/units/modules/network/f5/test_bigip_message_routing_route.py

adding bigip message routing route module

---

docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_message_routing_router.py
test/integration/bigip_message_routing_router.yaml
test/integration/targets/bigip_message_routing_peer/defaults/main.yaml
test/integration/targets/bigip_message_routing_router/defaults/main.yaml
test/integration/targets/bigip_message_routing_router/tasks/main.yaml
test/integration/targets/bigip_message_routing_router/tasks/setup.yaml
test/integration/targets/bigip_message_routing_router/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_generic_router.json
test/units/modules/network/f5/test_bigip_message_routing_router.py

adds message routing router module

---

docs/modules/bigip_message_routing_route_module.rst
docs/modules/bigip_message_routing_router_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_message_routing_protocol.py
test/integration/bigip_message_routing_protocol.yaml
test/integration/targets/bigip_message_routing_protocol/defaults/main.yaml
test/integration/targets/bigip_message_routing_protocol/tasks/main.yaml
test/units/modules/network/f5/fixtures/load_generic_parser.json
test/units/modules/network/f5/test_bigip_message_routing_peer.py
test/units/modules/network/f5/test_bigip_message_routing_protocol.py
test/units/modules/network/f5/test_bigip_message_routing_router.py

adds generic protocol parser module

---

docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_message_routing_transport_config.py
test/integration/bigip_message_routing_transport_config.yaml
test/integration/targets/bigip_message_routing_transport_config/defaults/main.yaml
test/integration/targets/bigip_message_routing_transport_config/tasks/main.yaml
test/integration/targets/bigip_message_routing_transport_config/tasks/setup.yaml
test/integration/targets/bigip_message_routing_transport_config/tasks/teardown.yaml
test/integration/targets/bigip_message_routing_transport_config/templates/irule-02.tcl
test/units/modules/network/f5/fixtures/load_generic_transport_config.json
test/units/modules/network/f5/test_bigip_message_routing_router.py
test/units/modules/network/f5/test_bigip_message_routing_transport_config.py

adds message routing transport config

---

docs/modules/bigip_device_certificate_module.rst
docs/modules/bigip_firewall_log_profile_network_module.rst
docs/modules/bigip_firewall_schedule_module.rst
docs/modules/bigip_message_routing_peer_module.rst
docs/modules/bigip_message_routing_protocol_module.rst
docs/modules/bigip_message_routing_route_module.rst
docs/modules/bigip_message_routing_router_module.rst
docs/modules/bigip_snat_pool_module.rst
docs/modules/bigip_vcmp_guest_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_device_certificate.py
library/modules/bigip_message_routing_route.py
test/integration/bigip_device_certificate.yaml
test/integration/targets/bigip_device_certificate/defaults/main.yaml
test/integration/targets/bigip_device_certificate/tasks/main.yaml
test/units/modules/network/f5/test_bigip_device_certificate.py

adds module to renew and generate device self-signed certificates

---

docs/modules/bigip_data_group_module.rst
docs/modules/bigip_firewall_rule_module.rst
library/modules/bigip_data_group.py
library/modules/bigip_device_info.py
library/modules/bigip_firewall_log_profile.py
test/integration/targets/bigip_data_group/tasks/issue-01346.yaml
test/integration/targets/bigip_data_group/tasks/main.yaml

fixes #1346 
fixes #1347 
fixes #1357

Multiple fixes

---

examples/0005-ha-pair-setup/playbook.yaml

removing allow service all as it shouldn't be default example

small doc update

---

.travis.yml
docs/modules/bigip_pool_module.rst
docs/modules/bigip_snat_translation_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_pool.py
library/modules/bigip_virtual_server.py
library/plugins/terminal/bigip.py
shippable.yml
test/integration/targets/bigip_command/tasks/provider-cli/issue-01407.yaml
test/integration/targets/bigip_command/tasks/provider-cli/main.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01403.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml
test/units/modules/network/f5/test_bigip_device_connectivity.py
test/units/modules/network/f5/test_bigip_gtm_wide_ip.py
test/units/modules/network/f5/test_bigip_monitor_http.py
test/units/modules/network/f5/test_bigip_monitor_https.py
test/units/modules/network/f5/test_bigip_monitor_tcp.py
test/units/modules/network/f5/test_bigip_monitor_tcp_echo.py
test/units/modules/network/f5/test_bigip_monitor_tcp_half_open.py
test/units/modules/network/f5/test_bigip_monitor_udp.py
test/units/modules/network/f5/test_bigip_remote_syslog.py
test/units/modules/network/f5/test_bigip_selfip.py

fixes #1403 
fixes #1402 
fixes #1404

Mutliple fixes

---

library/modules/bigip_provision.py
test/integration/targets/bigip_provision/tasks/issue-01307.yaml
test/integration/targets/bigip_provision/tasks/main.yaml
test/integration/targets/bigip_provision/tasks/setup.yaml
test/integration/targets/bigip_provision/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_sys_provision_default.json
test/units/modules/network/f5/test_bigip_provision.py

fixes #1307 
- adds support for urldb module
- adds support for sslo module
- adds support for cgnat module when using tmos 15.0
- adds support for modifying mgmt reserved memory
- updated unit test
- created new integration tasks
- added setup and teardown tasks to default big-ip module configuration for integration test

github issue 01307

---

docs/modules/bigip_apm_acl_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_apm_acl.py
test/integration/bigip_apm_acl.yaml
test/integration/targets/bigip_apm_acl/tasks/main.yaml
test/integration/targets/bigip_apm_acl/tasks/setup.yaml
test/integration/targets/bigip_apm_acl/tasks/teardown.yaml
test/integration/targets/bigip_apm_policy_fetch/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_apm_acl.json
test/units/modules/network/f5/test_bigip_apm_acl.py

adds APM ACL module

---

docs/modules/bigip_apm_acl_module.rst
docs/modules/bigip_provision_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/module_utils/network/f5/common.py
library/modules/bigip_apm_acl.py
library/modules/bigip_apm_network_access.py
test/integration/bigip_apm_acl.yaml
test/integration/bigip_apm_network_access.yaml
test/integration/bigip_snat_translation.yaml
test/integration/targets/bigip_apm_network_access/defaults/main.yaml
test/integration/targets/bigip_apm_network_access/tasks/main.yaml
test/integration/targets/bigip_apm_network_access/tasks/setup.yaml
test/integration/targets/bigip_apm_network_access/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_apm_network_access.json
test/units/modules/network/f5/test_bigip_apm_network_access.py

adds network access module

---

library/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-01391.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

I've not modified existing tests to change bigip_device_facts to bigip_device_info. Instead, I've added a new test for the issue.
The assert for checking the existence of the correct VLAN seems a little wonky to me. Can you please take a look at it @wojtek0806? Thanks!

fixes #1391

---

library/module_utils/network/f5/icontrol.py

This reverts commit d4622eba877b5cae7e54b51d69ea1dc4c086b438, reversing
changes made to 59197743213e908f0f2749f6ec2c5a9bb74fb213.

Revert "Merge pull request #1420 from crosbygw/devel"

---

docs/modules/bigip_apm_network_access_module.rst
library/module_utils/network/f5/icontrol.py
library/modules/bigip_asm_policy_fetch.py

fixes #1408

---

library/modules/bigip_monitor_http.py
library/modules/bigip_monitor_https.py
library/modules/bigip_vcmp_guest.py
test/integration/targets/bigip_monitor_http/tasks/issue-01377.yaml
test/integration/targets/bigip_monitor_http/tasks/main.yaml
test/integration/targets/bigip_monitor_http/vars/issue-01377.yaml
test/integration/targets/bigip_monitor_https/tasks/issue-01377.yaml
test/integration/targets/bigip_monitor_https/tasks/main.yaml
test/integration/targets/bigip_monitor_https/vars/issue-01377.yaml

fixes #1377

---

library/module_utils/network/f5/common.py
library/modules/bigip_apm_acl.py
library/modules/bigip_apm_network_access.py
library/modules/bigip_apm_policy_import.py
library/modules/bigip_cli_alias.py
library/modules/bigip_cli_script.py
library/modules/bigip_command.py
library/modules/bigip_config.py
library/modules/bigip_device_certificate.py
library/modules/bigip_device_dns.py
library/modules/bigip_device_info.py
library/modules/bigip_firewall_log_profile.py
library/modules/bigip_gtm_topology_region.py
library/modules/bigip_iapp_template.py
library/modules/bigip_message_routing_transport_config.py
library/modules/bigip_monitor_dns.py
library/modules/bigip_node.py
library/modules/bigip_profile_client_ssl.py
library/modules/bigip_profile_http.py
library/modules/bigip_provision.py
library/modules/bigip_snat_translation.py
library/modules/bigip_ucs.py
library/modules/bigip_user.py
library/modules/bigip_vlan.py
library/modules/bigiq_application_fastl4_tcp.py
library/modules/bigiq_application_fastl4_udp.py
library/modules/bigiq_application_https_offload.py
library/modules/bigiq_device_discovery.py
library/plugins/doc_fragments/f5.py

fixes from upstreaming to core

various upstream errors fixed

---

library/module_utils/network/f5/bigip.py
library/modules/bigip_software_install.py

fixes handling tomcat daemon lagging behind during restarts

---

library/modules/bigip_gtm_pool_member.py
library/modules/bigip_pool.py
library/modules/bigip_pool_member.py

enchanced documentation and some of the error messages for better user experience

doc enchancements

---

library/modules/bigip_device_ntp.py

adds first iteration of ansible checkmode diff

---

library/modules/bigip_snat_pool.py
library/modules/bigip_snat_translation.py
test/integration/bigip_snat_translation.yaml
test/integration/targets/bigip_snat_pool/tasks/issue-01284.yaml
test/integration/targets/bigip_snat_pool/tasks/issue-01428.yaml
test/integration/targets/bigip_snat_pool/tasks/main.yaml
test/integration/targets/bigip_snat_pool/vars/issue-01428.yaml
test/integration/targets/bigip_snat_translation/tasks/issue-01428.yaml
test/integration/targets/bigip_snat_translation/tasks/main.yaml
test/integration/targets/bigip_snat_translation/vars/issue-01428.yaml

adds RD capability to snatpool and snat translation modules
adds diff capability

fixes #1428

---

docs/modules/bigip_gtm_pool_member_module.rst
docs/modules/bigip_monitor_ldap_module.rst
docs/modules/bigip_pool_member_module.rst
docs/modules/bigip_pool_module.rst
docs/modules/bigip_snat_pool_module.rst
docs/modules/bigip_snat_translation_module.rst
docs/modules/bigip_software_install_module.rst
library/modules/bigip_snat_pool.py
test/integration/targets/bigip_snat_pool/tasks/issue-01429.yaml
test/integration/targets/bigip_snat_pool/tasks/main.yaml
test/integration/targets/bigip_snat_pool/vars/issue-01429.yaml

adds the ability fo specify snat translations as members

fixes #1429

---

library/modules/bigip_dns_zone.py

- fixes #1418 
- added additional examples, including example using a list of name servers as requested.

fixes 1418

---

test/integration/targets/bigip_node/tasks/issue-01381.yaml
test/integration/targets/bigip_node/tasks/main.yaml

fixed issue, added idempotency check, moved head to latest.

integration test for issue #1381

---

docs/modules/bigip_cgnat_lsn_pool_module.rst
docs/modules/bigip_dns_zone_module.rst
docs/modules/bigip_gtm_pool_member_module.rst
docs/modules/bigip_gtm_wide_ip_module.rst
docs/modules/bigip_pool_member_module.rst
docs/modules/bigip_pool_module.rst
docs/modules/bigip_virtual_address_module.rst
docs/modules/list_of_all_modules.rst
docs/modules/list_of_network_modules.rst
docs/modules/partner_maintained.rst
library/modules/bigip_apm_acl.py
library/modules/bigip_apm_network_access.py
library/modules/bigip_cgnat_lsn_pool.py
test/integration/bigip_cgnat_lsn_pool.yaml
test/integration/targets/bigip_cgnat_lsn_pool/defaults/main.yaml
test/integration/targets/bigip_cgnat_lsn_pool/tasks/main.yaml
test/integration/targets/bigip_cgnat_lsn_pool/tasks/setup.yaml
test/integration/targets/bigip_cgnat_lsn_pool/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_cgnat_lsn_pool.json
test/units/modules/network/f5/test_bigip_apm_acl.py
test/units/modules/network/f5/test_bigip_apm_network_access.py
test/units/modules/network/f5/test_bigip_cgnat_lsn_pool.py

adds lsn cgnat pool module

---

library/modules/bigip_asm_policy_import.py
requirements.readthedocs.txt
test/integration/targets/bigip_asm_policy_import/defaults/main.yaml
test/integration/targets/bigip_asm_policy_import/tasks/issue-01490.yaml
test/integration/targets/bigip_asm_policy_import/tasks/main.yaml
test/integration/targets/bigip_asm_policy_import/tasks/v2-policy.yaml

fixes #1490

---

library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01470.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml

fixes #1470

---

library/modules/bigip_wait.py
test/integration/targets/bigip_wait/tasks/issue_vcmp_wait.yaml
test/integration/targets/bigip_wait/tasks/main.yaml
test/units/modules/network/f5/test_bigip_wait.py

First PR. Just want to know if I'm on the right track.

adding type to bigip_wait, including VCMP as an option

---

devtools/stubs/library_module.py
library/modules/bigip_network_globals.py
test/integration/bigip_network_globals.yaml
test/integration/targets/bigip_network_globals/tasks/main.yaml
test/integration/targets/bigip_network_globals/tasks/setup.yaml
test/integration/targets/bigiq_utility_license_assignment/defaults/main.yaml
test/units/modules/network/f5/fixtures/load_dag_globals.json
test/units/modules/network/f5/fixtures/load_lldp_globals.json
test/units/modules/network/f5/fixtures/load_mcast_globals.json
test/units/modules/network/f5/fixtures/load_stp_globals.json
test/units/modules/network/f5/test_bigip_network_globals.py

Adds network globals module

---

library/plugins/action/bigip.py
library/plugins/action/bigip_imish_config.py
library/plugins/action/bigiq.py
library/plugins/lookup/bigiq_license.py
tasks/__init__.py
tasks/plugins.py

corrected imports in plugins

---

library/modules/bigip_virtual_server.py
tasks/module_doc_fragments.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01430.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml

fixes #1430

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01413.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

fixes #01413
- added option to allow http_uri and http_host conditions when using enable with asm policy.
- added integration test

issue-01413

---

library/modules/bigip_profile_client_ssl.py
library/modules/bigip_profile_fastl4.py
library/modules/bigip_profile_http.py
library/modules/bigip_profile_tcp.py
test/integration/targets/bigip_profile_client_ssl/tasks/issue-01532.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/main.yaml
test/integration/targets/bigip_profile_fastl4/tasks/issue-01532.yaml
test/integration/targets/bigip_profile_fastl4/tasks/main.yaml
test/integration/targets/bigip_profile_tcp/tasks/issue-01532.yaml
test/integration/targets/bigip_profile_tcp/tasks/main.yaml

Various improvements

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01543.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

This should allow creation of a http_host with a NOT condition.

Fixes #1543

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01546.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

Adds the reset action, with a new field called event, but with only one option - ssl_client_hello
Need comments on whether this is the right approach.

Fixes #1546

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01545.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

Adds ssl_extension condition, with handling for ssl_client_hello and ssl_server_hello events.
Does not handle datagroup option for SSL Extension.

Fixes #1545

---

devtools/stubs/library_module.py
library/modules/bigip_cgnat_lsn_pool.py
library/modules/bigip_profile_ftp.py
tasks/lib/stubber.py
tasks/module.py
test/integration/bigip_profile_ftp.yaml
test/integration/targets/bigip_profile_ftp/defaults/main.yaml
test/integration/targets/bigip_profile_ftp/tasks/main.yaml
test/integration/targets/bigip_profile_ftp/tasks/setup.yaml
test/integration/targets/bigip_profile_ftp/tasks/teardown.yaml
test/units/modules/network/f5/fixtures/load_ltm_profile_ftp.json
test/units/modules/network/f5/test_bigip_profile_ftp.py

adds ltm profile ftp module

---

library/module_utils/network/f5/connection.py
library/plugins/doc_fragments/f5.py
library/plugins/filter/abspath.py
library/plugins/filter/markdev.py
library/plugins/filter/q.py
library/plugins/lookup/bigiq_license.py
tasks/test.py

corrected sanity tests to test everything

corrected sanity tests to test everything

---

library/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-01563.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml
test/integration/targets/bigip_device_info/vars/issue-01563.yaml

A simpler fix for this issue, using existing library functions.

Fixes #1563

---

library/modules/bigip_network_globals.py
test/integration/targets/bigip_network_globals/tasks/issue-01581.yaml
test/integration/targets/bigip_network_globals/tasks/main.yaml
test/integration/targets/bigip_network_globals/vars/issue-01581.yaml

added self allow option

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01405.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

adds persist cookie option to rule

---

library/modules/bigip_profile_client_ssl.py

fixes #1440

---

library/modules/bigip_imish_config.py

fixes #1392

---

README.rst

Reverts F5Networks/f5-ansible#1613

Revert "update devel build link"

---

library/modules/bigiq_device_info.py
test/integration/targets/bigiq_device_info/tasks/fmfa-347.yaml
test/integration/targets/bigiq_device_info/tasks/main.yaml

I experienced problems while rebasing commits. In order to resolve it, I had to re-create my PR. 
This is continuation for the following change https://github.com/F5Networks/f5-ansible/pull/1623

FMFA-347: Update bigiq_device_info module to support 7.0 version

---

library/modules/bigip_software_install.py
test/units/modules/network/f5/test_bigip_software_install.py

Fixes the issue where bigip_software_install fails for multiblade systems.

Fixes #1634

---

library/modules/bigip_profile_client_ssl.py

This change is intended to resolve problem  crt-key objects not found without providing extension in name
- Update bigip_profile_client_ssh module to correctly use true_name parameter within cert_key_chain

FMFA-430: Update bigip_profile_client_ssl module to resolve problem with using true_name parameter

---

library/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-01630.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml
test/units/modules/network/f5/test_bigip_device_auth_ldap.py

Fixes 1630

---

library/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-01497.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

fixes 1497

---

library/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/issue-01610.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml
test/units/modules/network/f5/test_bigip_virtual_server.py

Somehow the idempotency test is failing.

Fixes #1610

---

devtools/stubs/tests_unit_module.py
library/modules/bigip_device_connectivity.py
library/modules/bigip_device_dns.py
library/modules/bigip_device_group.py
library/modules/bigip_device_group_member.py
library/modules/bigip_device_ha_group.py
library/modules/bigip_device_httpd.py
library/modules/bigip_device_info.py
library/modules/bigip_device_license.py
library/modules/bigip_device_ntp.py
library/modules/bigip_device_sshd.py
library/modules/bigip_device_syslog.py
test/integration/targets/bigip_device_ha_group/tasks/setup.yaml
test/integration/targets/bigip_device_httpd/tasks/main.yaml
test/integration/targets/bigip_device_httpd/tasks/teardown.yaml
test/integration/targets/bigip_device_info/tasks/issue-00082.yaml
test/integration/targets/bigip_device_info/tasks/issue-00289.yaml
test/integration/targets/bigip_device_info/tasks/issue-01094.yaml
test/integration/targets/bigip_device_info/tasks/issue-01095.yaml
test/integration/targets/bigip_device_info/tasks/issue-01159.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

fixes issues in functional tests
tests on v15 pass
adds route domain to allowed parameters in bigip_device_info
adds route domain docs to device_info metadata

fmfa_445_446

---

library/modules/bigip_device_auth_radius.py
test/integration/bigip_device_auth_radius.yaml
test/integration/targets/bigip_device_auth_radius/tasks/main.yaml
test/units/modules/network/f5/fixtures/load_radius_config.json
test/units/modules/network/f5/fixtures/load_radius_server.json
test/units/modules/network/f5/test_bigip_device_auth_radius.py

**Summary**
This change introduces new bigip_device_auth_radius module intended for enabling RADIUS auth
**Chnages**
Add new module titled as bigip_device_auth_radius
Add unit tests for new module
Add Functional tests for new module
**Additional Information**

Add bigip_device_auth_radius module

---

library/modules/bigip_data_group.py

fixes list type issue

---

README.rst
devtools/stubs/library_module.py
library/modules/bigip_device_traffic_group.py
library/modules/bigip_device_trust.py
library/modules/bigip_dns_cache_resolver.py
library/modules/bigip_dns_nameserver.py
library/modules/bigip_dns_resolver.py
library/modules/bigip_dns_zone.py
library/modules/bigip_file_copy.py
library/modules/bigip_firewall_address_list.py
library/modules/bigip_firewall_dos_profile.py
library/modules/bigip_firewall_dos_vector.py
test/integration/targets/bigip_device_traffic_group/tasks/issue-01216.yaml
test/integration/targets/bigip_device_traffic_group/vars/issue-01216.yaml

updated on device methods for better error handling
tested batch of modules against v15
updated templates and links due to new collection release

various fixes

---

library/modules/bigip_monitor_mysql.py
test/integration/bigip_monitor_mysql.yaml
test/integration/targets/bigip_monitor_mysql/defaults/main.yaml
test/integration/targets/bigip_monitor_mysql/tasks/main.yaml
test/units/modules/network/f5/fixtures/load_bigip_monitor_mysql.json
test/units/modules/network/f5/test_bigip_monitor_mysql.py

This change is intended to add a new module intended to configure BIGIP Monitor for MySQL. 
Internal ticket: FMFA-431
- Add bigip_monitor_mysql module
- Add unit tests for new bigip_monitor_module
- Add integration test for new bigip_monitor_module
WIP status will be resolved when MR will be ready to be approved and merged

Add mysql bigip monitor module

---

.travis.yml
library/modules/_bigip_device_facts.py
library/modules/_bigiq_device_facts.py
tasks/lib/common.py
tasks/lib/upstream.py
tasks/module.py
tasks/module_doc_fragments.py
tasks/module_utils.py
tasks/plugins.py
tasks/test.py
test/integration/bigiq_device_info.yaml
test/integration/targets/bigiq_device_info/tasks/issue-00921.yaml
test/integration/targets/bigiq_device_info/tasks/issue-00922.yaml
test/integration/targets/bigiq_device_info/tasks/issue-00923.yaml

increased robustness of upstream scripts

increased robustness of upstream scripts

---

library/modules/bigip_firewall_global_rules.py
library/modules/bigip_firewall_log_profile.py
library/modules/bigip_firewall_log_profile_network.py
library/modules/bigip_firewall_policy.py
library/modules/bigip_firewall_port_list.py
library/modules/bigip_firewall_rule.py
library/modules/bigip_firewall_rule_list.py
library/modules/bigip_firewall_schedule.py
library/modules/bigip_gtm_datacenter.py
library/modules/bigip_gtm_global.py
test/integration/targets/bigip_firewall_rule/tasks/teardown.yaml
test/integration/targets/bigip_firewall_rule_list/tasks/issue-00489.yaml

improves on_device methods
validates modules for v15

fmfa468_469

---

library/modules/bigip_device_auth_ldap.py
test/integration/targets/bigip_device_auth_ldap/tasks/issue-01182.yaml
test/integration/targets/bigip_device_auth_ldap/tasks/main.yaml

fixes #1182

---

library/modules/bigip_ssl_csr.py
test/integration/bigip_ssl_csr.yaml
test/integration/targets/bigip_ssl_csr/defaults/main.yaml
test/integration/targets/bigip_ssl_csr/tasks/main.yaml
test/integration/targets/bigip_ssl_csr/tasks/setup.yaml
test/units/modules/network/f5/fixtures/load_sys_crypto_csr.json
test/units/modules/network/f5/test_bigip_ssl_csr.py

There are going to be two parts to this fix. Creating this module is the first part.

Fixes #1275 partially

---

README.rst

slack readme info

---

library/modules/bigip_gtm_dns_listener.py
test/integration/bigip_gtm_dns_listener.yaml
test/integration/targets/bigip_gtm_dns_listener/defaults/main.yaml
test/integration/targets/bigip_gtm_dns_listener/tasks/main.yaml
test/integration/targets/bigip_gtm_dns_listener/tasks/setup.yaml
test/integration/targets/bigip_gtm_dns_listener/tasks/teardown.yaml
test/units/modules/network/f5/test_bigip_gtm_dns_listener.py

This change is intended to add GTM DNS Listener module. 
- Add new bigip_gtm_dns_listener module 
- Add unit test for new module
- Add functional tests for new module

FMFA-418: Add BIGIP GTM DNS Listener module

---

library/modules/bigip_device_certificate.py
library/modules/bigip_lx_package.py
library/modules/bigip_management_route.py
library/modules/bigip_message_routing_peer.py
library/modules/bigip_message_routing_protocol.py
library/modules/bigip_message_routing_route.py
library/modules/bigip_message_routing_router.py
library/modules/bigip_message_routing_transport_config.py
library/modules/bigip_monitor_dns.py
library/modules/bigip_monitor_external.py
library/modules/bigip_monitor_ftp.py
library/modules/bigip_monitor_gateway_icmp.py
library/modules/bigip_monitor_http.py
library/modules/bigip_monitor_icmp.py
library/modules/bigip_monitor_ldap.py
library/modules/bigip_monitor_mysql.py
library/modules/bigip_monitor_oracle.py
library/modules/bigip_monitor_smtp.py
library/modules/bigip_monitor_snmp_dca.py
library/modules/bigip_monitor_tcp.py
library/modules/bigip_monitor_tcp_echo.py
library/modules/bigip_monitor_tcp_half_open.py
library/modules/bigip_monitor_udp.py
library/modules/bigip_network_globals.py
library/plugins/doc_fragments/f5ssh.py
test/integration/targets/bigip_monitor_gateway_icmp/tasks/issue-01074.yaml

batch tested modules on v15
corrected minor bugs
changed on_device methods on another set of modules

fmfa_507_508

---

library/modules/bigip_lx_package.py
test/integration/targets/bigip_lx_package/tasks/issue-00730.yaml
test/integration/targets/bigip_lx_package/tasks/issue-01717.yaml
test/integration/targets/bigip_lx_package/tasks/main.yaml
test/units/modules/network/f5/test_bigip_lx_package.py

Added the ability to check for existence of file on BIG-IP and if it's present, to not upload it again.
Tested manually. What's a good way to upload the rpm file through one of the BIG-IP modules?

Fixes #1717

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_provision.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_provision.py

Still considering what type of testing to write. If a test for VCMP guests already exists, then that's all that's needed

possible fix for #1105

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_radius.py

fixes #1760

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_license.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_device_license.py
test/integration/targets/bigip_device_license/tasks/issue-1810.yaml
test/integration/targets/bigip_device_license/tasks/main.yaml

This change is intended to include new option which will be used for license renewal
- Update bigip_device_license module to include new option
- Update unit tests for bigip_device_license module
- Update integration tests for bigip_device_license module

bigip_device_license add renew option

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1710-add-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1777-add-syslog-device-info.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-01777.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

New options bigip device info

---

ansible_collections/f5networks/f5_modules/changelogs/changelog.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1217-new-bigp-ssl-key-cert.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1710-add-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1728-bugfix-command.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1777-add-syslog-device-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1778-sync-status-bigip-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1782-add-reuse-objects.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1784-add-apm-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1816-license-renew.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1832-remove-deprecations.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1834-atc-add-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1834-atc-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1840-bugfix-lxpackage-configsync.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1855-add-api-protect-apm.yaml

@wojtek0806, minor edits to changelog and fragments

Changelog edits

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1507-change-ucs_fetch-async.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py
test/integration/targets/bigip_ucs_fetch/tasks/main.yaml

fixes #1507

---

test/integration/targets/bigip_profile_http/tasks/issue-01022.yaml

It seems the code change already exists.

Fixes #1869

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py

@wojtek0806, this was causing build failures (that that), guess i missed it in the edits.  Please merge when you get a chance.

minor edit to module text

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1853-fix-firewall-address-list-error.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py

Primary testing itself was failing with v15.

Fixes #1853

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py

Minor change to this description per FM-682.

updated bigip_ucs_fetch per fm682

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1800-fix-bigip-pool-reuse-node.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py
test/integration/targets/bigip_pool_member/tasks/provider/issue-01800.yaml
test/integration/targets/bigip_pool_member/tasks/provider/main.yaml

fixes #1800

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py

adds docs explaining how to enable MRF router option.

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1835-add-http-header-condition-policy-rule.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1876-add-disable-action-policy-rule.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1880-add-event-type-to-reset-action-policy-rule.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01835.yaml
test/integration/targets/bigip_policy_rule/tasks/issue-01876.yaml
test/integration/targets/bigip_policy_rule/tasks/issue-01880.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

fixes #1876
fixes #1835
fixes #1880

bigip_policy_improvements

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1873-add-policy-condition-type-tcp-bigip-policy-rule.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01873.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

updated fix for support condition type TCP
fixes #1873

updated fix for support condition type TCP

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py

removes redundant code

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1985-add-bigiq-token-refresh.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/bigiq.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py

adds token handling to bigiq_device_discovery
fixes #1969

adds bigiq token refresh

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1920-fix-gtm-wideip-wildcardtype.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/common.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/issue-01920.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/main.yaml
test/integration/targets/bigip_gtm_wide_ip/vars/issue-01920.yaml

Allow wild card type for gtm wide ip

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-v15-v16-tests-http-profile.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_http.py
test/integration/targets/bigip_profile_http/tasks/issue-01310.yaml
test/integration/targets/bigip_profile_http/vars/issue-01310.yaml

add more choices to request and response chunking parameters to accomodate v15 TMOS and above

http_profile_fixes

---

ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_device_info.py

Fix bigip info

---

ansible_collections/f5networks/f5_modules/CHANGELOG.rst
ansible_collections/f5networks/f5_modules/changelogs/changelog.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2061-fix-bigip-command-cli-teem.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_wait.py
fragments_archive/1.10.1/2061-fix-bigip-command-cli-teem.yaml

Bigip command fix

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2041-add-serialNumber-sslcerts-gatherSubset.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py

Include serialNumber for ssl-certs gather_subset

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1912-add-syn_cookie_enable.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_fastl4.py
test/integration/targets/bigip_profile_fastl4/tasks/issue-01912.yaml
test/integration/targets/bigip_profile_fastl4/tasks/main.yaml

add syn_cookie_enable parameter to bigip_profile_fastl4 module

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-asm-api-filters.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_import.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_manage.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_server_technology.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_signature_set.py
test/integration/targets/bigip_asm_policy_import/tasks/issue-02067.yaml
test/integration/targets/bigip_asm_policy_import/tasks/main.yaml

workaround for broken API filters for ASM policies

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2083-fix-bigip-policy.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-02083.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml
test/integration/targets/bigip_policy_rule/tasks/teardown.yaml

fix tcp condition to be allowed with asm_policy action

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2104-add-auto_last_hop.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/environment/issue-02104.yaml
test/integration/targets/bigip_virtual_server/tasks/environment/main.yaml

Fixes #2104 
Tests:
(venv-3.9) ➜  repro$ ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_virtual_server.yaml -t "issue-02104" --step
PLAY [Metadata of bigip_virtual_server] ******************************************************************************************************************************************
PLAY [Test the bigip_virtual_server module - Environment] ************************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************************************************************
TASK [Gathering Facts] …

Added auto_last_hop parameter for bigip_virtual_server module

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-bigip-wait-send-teem-error.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py
ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_pool.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_server.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_topology_record.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_virtual_server.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_node.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_wait.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py
ansible_collections/f5networks/f5_modules/tests/unit/mock/loader.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_cgnat_lsn_pool.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_device_auth_radius.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_wait.py

fixing linting issues

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py

@wojtek0806, a couple minor edits here.

Doc edit dec

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1687-add-filter-and-paging-logic.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/1984-bigip-device-info-changes.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2143-fix-partition-filter.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2145-fix-false-positive-errors.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-security-parameter-ldap-monitor.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-infraano449.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

add GTM VS stats into bigip_device_info

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_fetch.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_manage.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_firepass.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_http.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_https.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ike_peer.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_server_ssl.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_smtp.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_user.py

@wojtek0806, here is the PR for my minor changes to the documentation for this repo.

Minor documentation edits

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/add_content_type_include.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_http_compression.py
test/integration/targets/bigip_profile_http_compression/tasks/main.yaml

Added parameter content_type_include to bigip_profile_http_compression
```
repro ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_profile_http_compression.yaml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: file /Users/r.upadhyay/Documents/github/f5_ansible_dev_workspace/f5-ansible/test/integration/targets/bigip_profile_http_compression/tasks/setup.yaml is empty and had
no tasks to include
[WARNING]: file /Users/r.upadhyay/Documents/github/f5_ansible_dev_workspace/f5-ansible/test/integration/targets/bigip_profile_http_compression/tasks/teardown.yaml is empty and
had no tasks to include
PLAY [Metadata of bigip_profile_http_compression] ********************************************************************** …
```

Added param content_type_include

---

.travis.yml
ansible_collections/f5networks/f5_modules/changelogs/fragments/bugfix-gtm-wide-ip.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py
requirements.travis.txt
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/issue-disabled.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/main.yaml

This fix allows the user to create gtm wide ips in disabled state.
test output:
```
ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_gtm_wide_ip.yaml -t "issue-disabled"
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: Found both group and host with same name: velos-controller
[WARNING]: Found both group and host with same name: velos-partition
PLAY [Metadata of bigip_gtm_wide_ip] *****************************************************************************************************************************
PLAY [Test the bigip_gtm_wide_ip module - Environment] ***********************************************************************************************************
TASK [Gathering Facts] …
```

bugfix for bigip_gtm_wide_ip

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/add-meta-choice-packages.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/bugfix-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-02123.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

Fix for #2123 
```
ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_device_info.yaml -t "issue-02123"
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
PLAY [Metadata of bigip_device_info] *****************************************************************************************************************************
PLAY [Test the bigip_device_info module] *************************************************************************************************************************
TASK [Gathering Facts] *******************************************************************************************************************************************
ok: [bigip1]
TASK [bigip_device_info : Get packages info] …
```

Added meta option, packages, along with bugfix in bigip_device_info

---

ansible_collections/f5networks/f5_modules/README.md
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py

Minor edits to the docs modified for the release.

Documentation review

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2177-add-ucs-date.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py

Add ucs date and time to device info

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_snmp_trap.py
test/integration/targets/bigip_snmp_trap/defaults/main.yaml
test/integration/targets/bigip_snmp_trap/tasks/infraano-00086.yaml
test/integration/targets/bigip_snmp_trap/tasks/main.yaml

adding support for snmp trap v3

adding support for snmp trap v3

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ltm_global.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/fixtures/load_ltm_global_settings_general.json
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_gtm_global.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_ltm_global.py
test/integration/bigip_ltm_global.yaml
test/integration/targets/bigip_ltm_global/meta/main.yml
test/integration/targets/bigip_ltm_global/tasks/main.yaml

add ltm global

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2013-add-addon-bigiq-license.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license.py
test/integration/targets/bigiq_regkey_license/tasks/issue-02013.yaml

add addon_keys parameter

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2163-fix-getting-ip-from-destination.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_http.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_https.py
test/integration/targets/bigip_monitor_http/tasks/issue-02163.yaml
test/integration/targets/bigip_monitor_http/tasks/main.yaml
test/integration/targets/bigip_monitor_https/tasks/issue-02163.yaml
test/integration/targets/bigip_monitor_https/tasks/main.yaml

Fixes #2163 
bigip_monitor_https
```
ansible-playbook ../f5-ansible/test/integration/bigip_monitor_https.yaml -t "issue-02163"
PLAY [Metadata of bigip_monitor_https] ***************************************************************************************************************************
PLAY [Test the bigip_monitor_https module] ***********************************************************************************************************************
TASK [Gathering Facts] *******************************************************************************************************************************************
ok: [bigip1]
TASK [bigip_monitor_https : Issue 02163 - Create HTTPS Monitor] ************************************************************************************************** …
```

fix bug when extracting ip from destination value

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_http.py

A couple small edits to the changed files for the release

Minor doc edits for release

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-idempotency-gtm-wide-ip.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py
test/integration/targets/bigip_gtm_wide_ip/tasks/provider/issue-00951.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/provider/issue-00954.yaml

Fixed a idempotency bugs in bigip_gtm_wide_ip
```
ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_gtm_wide_ip.yaml -t "provider"
PLAY [Metadata of bigip_gtm_wide_ip] *********************************************************************************************************************************************
PLAY [Test the bigip_gtm_wide_ip module - Environment] ***************************************************************************************************************************
ok: [bigip1]
PLAY [Test the bigip_gtm_wide_ip module - Provider] …
```

fixed idempotency bugs in bigip_gtm_wide_ip

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-pagination-bug-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-02209.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

Fixes #2209 
```
ansible-playbook ../f5-ansible/test/integration/bigip_device_info.yaml --step
PLAY [Metadata of bigip_device_info] *********************************************************************************************************************************************
PLAY [Test the bigip_device_info module] *****************************************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: ***********************************************************************************************************************
TASK [Gathering Facts] ************************************************************************************ …
```

Paging fix

---

ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py
ansible_collections/f5networks/f5_modules/plugins/module_utils/common.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py
test/integration/bigip_pool.yaml
test/integration/targets/bigip_pool/tasks/main.yaml
test/integration/targets/bigip_pool/tasks/sr-1-8210113510.yaml
test/integration/targets/bigip_pool/vars/sr-1-8210113510.yaml

Fixes #2199 and add support for #minimum up pool member   
Test Results:
```
ansible-playbook -i ~/devsettings/inventory/hosts.yaml ~/PycharmProjects/f5-ansible/test/integration/bigip_pool.yaml --tags "sr-1-8210113510"
PLAY [Metadata of bigip_pool] ***********************************************************************************************************************************************************
PLAY [Test the bigip_pool module] *******************************************************************************************************************************************************
TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [bigip_15_1]
TASK …
```

adding fix for pool min up member

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py

@urohit011, here are a few minor doc edits to the files in this repo

Doc edits for release

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/add-new-parameters-bigip-pool.yaml

added changelog for bigip_pool parameters addition

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-ldap-monitor-password.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_ldap.py
test/integration/targets/bigip_monitor_ldap/tasks/issue-02163.yaml
test/integration/targets/bigip_monitor_ldap/tasks/issue-02226.yaml
test/integration/targets/bigip_monitor_ldap/tasks/main.yaml

fixes ldap monitor password

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-idempotency-software-install.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py
test/integration/targets/bigip_software_install/tasks/main.yaml
test/integration/targets/bigip_software_install/tasks/sr-1-8372348301.yaml
test/integration/targets/bigip_software_install/vars/sr-1-8372348301.yaml

This PR is to fix [this](https://tron.f5net.com/sr/1-8372348301/) SR, it's regarding idempotency.

Fixed idempotency issue in bigip_software_install

---

.gitignore
ansible_collections/f5networks/f5_modules/changelogs/fragments/add-additional-telemetry-data.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/constants.py
ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py
ansible_collections/f5networks/f5_modules/tests/unit/module_utils/network/f5/test_teem.py

add additional telemetry data with relevant tests

fixed issue with module naming

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/add_only_create_file_to_qkview.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py
test/integration/targets/bigip_qkview/defaults/main.yaml
test/integration/targets/bigip_qkview/files/issue-2216.json
test/integration/targets/bigip_qkview/tasks/issue-02216.yaml
test/integration/targets/bigip_qkview/tasks/main.yaml

Fixes #2216 
```
ansible-playbook ../f5-ansible/test/integration/bigip_qkview.yaml
PLAY [Metadata of bigip_qkview] **************************************************************************************************************************************************
PLAY [Test the bigip_qkview module] **********************************************************************************************************************************************
ok: [bigip15]
TASK [bigip_qkview : Ensure qkview is absent before testing] ********************************************************************************************************* …
```

Added only_create_file option to bigip_qkview

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-hotfix-image-installation-on-vcmp.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py
test/integration/targets/bigip_software_install/tasks/main.yaml
test/integration/targets/bigip_software_install/tasks/vcmp.yaml

```
root@1-8507391901-ubuntu-server2:/etc/ansible# ansible-playbook play_test.yaml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect line
lengths
PLAY [Testing F5 Modules for Ansible] ********************************************************************************************************************************************
TASK [Install new OS] ************************************************************************************************************************************************************
changed: [10.170.10.197]
TASK [Assert Install new OS] **************************************************************************************************************************** …
```

Fixed bug in bigip_software_install related to hotfix installation

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-records-update-issues-data-group.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/compare.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py
test/integration/targets/bigip_data_group/tasks/issue-02246.yaml
test/integration/targets/bigip_data_group/tasks/main.yaml

Fixes #2246 . All tests are passing
```
PLAY [Metadata of bigip_data_group] ********************************************
PLAY [Test the bigip_data_group module] ****************************************
TASK [Gathering Facts] *********************************************************
ok: [bigip16]
TASK [bigip_data_group : Generic string internal data group file] **************
changed: [bigip16]
TASK [bigip_data_group : Assert Generic string internal data group file] *******
ok: [bigip16] => {
"changed": false,
"msg": "All assertions passed"
}
TASK [bigip_data_group : Generic string internal data group file - Idempotent check] ***
ok: [bigip16]
TASK [bigip_data_group : Assert Generic string internal data group file - Idempotent check] ***
ok: [bigip16] => {
"changed": false,
"msg": "All …
```

fixed bug related to record updation in bigip_data_group

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py

Minor documentation edits to the qkview file

minor doc edits to this file

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2227-fix-permission-ownership-bigip-ucs.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs.py
test/integration/targets/bigip_ucs/tasks/issue-2227.yaml
test/integration/targets/bigip_ucs/tasks/main.yaml

Fixes #2227 
```
ansible-playbook ../../f5-ansible/test/integration/bigip_ucs.yaml
PLAY [Metadata of bigip_ucs] *****************************************************************************************************************************************************
PLAY [Test the bigip_ucs module] *************************************************************************************************************************************************
ok: [bigip16]
TASK [bigip_ucs : Get temporary file for fetching UCS] *************************************************************************************************************** …
```

Fixed permission and ownership for uploaded ucs file

---

ansible_collections/f5networks/f5_modules/README.md
ansible_collections/f5networks/f5_modules/galaxy.yml
ansible_collections/f5networks/f5_modules/meta/runtime.yml
ansible_collections/f5networks/f5_modules/requirements.txt
devtools/scripts/merge-upstream.sh
devtools/stubs/collection_galaxy_f5_modules.yml

changed requirements file, indicated clearly that py 3.5 is required, dropped ansible 2.9 support

changes to files

---

README.rst
ansible_collections/f5networks/f5_modules/README.md

Doc edits for release content and rebranding per 868.

Minor doc updates

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1932-add-up-interval-bigip-monitor-http.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2052-add-remaining-host-conditions.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2252-add-referrals-device-auth-ldap.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2253-asm-disable-target-policy-rule.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/2261-asm-sync-bigip-device-group.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_group.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_http.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/fixtures/load_device_group.json
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_device_auth_ldap.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_device_group.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_monitor_http.py
test/integration/targets/bigip_device_auth_ldap/tasks/issue-02251.yaml
test/integration/targets/bigip_device_auth_ldap/tasks/main.yaml
test/integration/targets/bigip_device_group/tasks/issue-00806.yaml
test/integration/targets/bigip_device_group/tasks/issue-02261.yaml
test/integration/targets/bigip_device_group/tasks/main.yaml
test/integration/targets/bigip_monitor_http/tasks/issue-01932.yaml
test/integration/targets/bigip_monitor_http/tasks/main.yaml
test/integration/targets/bigip_policy_rule/tasks/issue-02052.yaml
test/integration/targets/bigip_policy_rule/tasks/issue-02253.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

fixes #1932 
fixes #2052
fixes #2251
fixes #2253
fixes #2261

Catchall for pending PRs

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py

@wojtek0806, only one file needed minor edits.

Minor doc edits 

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_server_ssl.py
fragments_archive/fix-profile-srverssl-issue01711.yaml
test/integration/targets/bigip_profile_server_ssl/tasks/issue-01609.yaml
test/integration/targets/bigip_profile_server_ssl/tasks/issue-01711.yaml
test/integration/targets/bigip_profile_server_ssl/tasks/main.yaml

fixes #1711
fixes #1609 
Test Results:
```
ansible-playbook -i ~/devsettings/inventory/hosts.yaml ~/PycharmProjects/f5-ansible/test/integration/bigip_profile_server_ssl.yaml --tags "issue-01711,issue-01609"
PLAY [Metadata of bigip_profile_server_ssl] *********************************************************************************************************************************************
PLAY [Test the bigip_profile_server_ssl module] *****************************************************************************************************************************************
TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [bigip_15_1]
TASK …
```

adding fix for issue 01711 and 01609

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2299-gui-audit-bigip-sys-global.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_sys_global.py
test/integration/targets/bigip_sys_global/defaults/main.yaml
test/integration/targets/bigip_sys_global/tasks/main.yaml
test/integration/targets/bigip_sys_global/tasks/teardown.yaml

feat: add gui_audit parameter to bigip_sys_global

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-passphrase-bug-bigip-ucs-fetch.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py

```
ansible-playbook ../../f5-ansible/test/integration/bigip_ucs_fetch.yaml
PLAY [Metadata of bigip_ucs_fetch] ***********************************************************************************************************************************************
PLAY [Test the bigip_ucs_fetch module] *******************************************************************************************************************************************
ok: [bigip16]
TASK [bigip_ucs_fetch : Remove backups] ************************************************************************************************************************************* …
```

fixing passphrase bug in bigip_ucs_fetch

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2290-firewall-rule-set-source-destination-to-any.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_rule.py
test/integration/targets/bigip_firewall_rule/tasks/issue-2290.yaml
test/integration/targets/bigip_firewall_rule/tasks/main.yaml

Closed #2290 
```
ansible-playbook ../../f5-ansible/test/integration/bigip_firewall_rule.yaml -t "issue-2290"
PLAY [Metadata of bigip_firewall_rule] *******************************************************************************************************************************************
PLAY [Test the bigip_firewall_rule module] ***************************************************************************************************************************************
ok: [bigip16]
TASK [bigip_firewall_rule : Create a basic firewall policy] ******************************************************************************* …
```

Allow setting source and destination to any in bigip_firewall_rule

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2294-device-info-ltm-policies-attributes.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-02294.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

Closes #2294 
```
ansible-playbook ../../f5-ansible/test/integration/bigip_device_info.yaml -t "issue-02294"
PLAY [Metadata of bigip_device_info] *********************************************************************************************************************************************
PLAY [Test the bigip_device_info module] *****************************************************************************************************************************************
ok: [bigip16]
TASK [bigip_device_info : Create published policy] ***************************************************************************************** …
```

Added more attributes for ltm policies in bigip_device_info

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2308-bigip-policy-host-contains.yaml
ansible_collections/f5networks/f5_modules/galaxy.yml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-02308.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

add host_contains condition to bigip_policy_rule.py

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/added-new-param-ssl-key-cert-modules.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_certificate.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py
test/integration/targets/bigip_ssl_certificate/tasks/issue-02306.yaml
test/integration/targets/bigip_ssl_certificate/tasks/main.yaml
test/integration/targets/bigip_ssl_key/tasks/issue-02306.yaml
test/integration/targets/bigip_ssl_key/tasks/main.yaml
test/integration/targets/bigip_ssl_key_cert/tasks/issue-02306.yaml
test/integration/targets/bigip_ssl_key_cert/tasks/main.yaml

Added true_names option to bigip_ssl_key_cert, bigip_ssl_key and bigip_ssl_certificate.

Added true_names option to modules working with ssl cert and key

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/2263-fix-bigip-device-info-fqdn-pool-interval.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py

fix bigip_device_info fqdn_up_interval and fqdn_down_interval

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/device-info-license-bugfix.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py

```
ansible-playbook ../../f5-ansible/test/integration/bigip_device_info.yaml -t "issue-license"
PLAY [Metadata of bigip_device_info] *********************************************************************************************************************************************
PLAY [Test the bigip_device_info module] *****************************************************************************************************************************************
ok: [bigip16a.com]
TASK [bigip_device_info : Gather License info] **************************************************************************************************** …
```

license info bugfix

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py

fixes #2258

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_provision_async.py

igip_command.py -  in the DOCUMENTATION section, edited the new note for the chdir.
bigip_provision_async.py - in the DOCUMENTATION section editing NEW descriptions and notes sections.

Doc edits for June release

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/virtual-server-profile-idempotency.yaml
ansible_collections/f5networks/f5_modules/plugins/doc_fragments/f5_rest_cli.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py
test/integration/targets/bigip_virtual_server/tasks/provider/main.yaml
test/integration/targets/bigip_virtual_server/tasks/provider/sr-00458196.yaml

Fixes the bug in SR-00458196
```
ansible-playbook ../playbooks/sr_vs.yaml
PLAY [INFRA-631] *****************************************************************************************************************************************************************
TASK [Provision ASM] *************************************************************************************************************************************************************
ok: [bigip17b.com]
TASK [Create blank ASM policy and activate] **************************************************************************************************************************************
changed: [bigip17b.com]
TASK [Assert Create blank ASM policy and activate] *********************************************************************************************** …
```

Vs profile

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/policy-rule-ssl-extension-options.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-02350.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

Closes #2350 
```
ansible-playbook ../../f5-ansible/test/integration/bigip_policy_rule.yaml -t "issue-02350"
PLAY [Metadata of bigip_policy_rule] *********************************************************************************************************************************************
PLAY [Test the bigip_policy_rule module] *****************************************************************************************************************************************
ok: [bigip17b.com]
TASK [bigip_policy_rule : Issue 02350 - Create published policy] ********************************************************************** …
```

Added more options for ssl_extension policy rule

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/bigip-pool-removeMonitor-bugfix.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py
test/integration/targets/bigip_pool/tasks/issue-2347.yaml
test/integration/targets/bigip_pool/tasks/main.yaml

Fixes #2347 
```
PLAY [Metadata of bigip_pool] ************************************************************************************************************************************
PLAY [Test the bigip_pool module] ********************************************************************************************************************************
TASK [bigip_pool : Issue-2347 Create a pool with monitor] ********************************************************************************************************
[WARNING]: Platform darwin on host 10.218.136.192 is using the discovered Python interpreter at /opt/homebrew/bin/python3.10, but future installation of another
Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.13/reference_appendices/interpr …
```

Issue-Fix : bigip_pool module is unable to remove monitors

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py

Copy editing descriptions for changed files.

doc edits Oct 11

---

.travis.yml
ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-gtm-monitors.yaml
ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-gtm-topo-region.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_bigip.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_firepass.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_http.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_https.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_tcp.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_monitor_tcp_half_open.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_topology_region.py
requirements.travis.txt
test/integration/targets/bigip_gtm_monitor_bigip/tasks/issue-02379.yaml
test/integration/targets/bigip_gtm_monitor_bigip/tasks/main.yaml
test/integration/targets/bigip_gtm_monitor_firepass/tasks/issue-02379.yaml
test/integration/targets/bigip_gtm_monitor_firepass/tasks/main.yaml
test/integration/targets/bigip_gtm_monitor_http/tasks/issue-02379.yaml
test/integration/targets/bigip_gtm_monitor_http/tasks/main.yaml
test/integration/targets/bigip_gtm_monitor_https/tasks/issue-02379.yaml
test/integration/targets/bigip_gtm_monitor_https/tasks/main.yaml
test/integration/targets/bigip_gtm_monitor_tcp/tasks/issue-02379.yaml
test/integration/targets/bigip_gtm_monitor_tcp/tasks/main.yaml
test/integration/targets/bigip_gtm_monitor_tcp_half_open/tasks/issue-02379.yaml
test/integration/targets/bigip_gtm_monitor_tcp_half_open/tasks/main.yaml
test/integration/targets/bigip_gtm_topology_region/tasks/issue-02376.yaml
test/integration/targets/bigip_gtm_topology_region/tasks/main.yaml

mutltiple-fixes

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/issue_2393.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_pool_member.py

Issue - 2393 fixed

---

devtools/stubs/collection_galaxy_f5_modules.yml

Added files to build_ignore in galaxt.yml

Galaxy tmpl

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/issue-2429.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_server.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_gtm_server.py
test/integration/targets/bigip_gtm_server/tasks/issue-02429.yaml
test/integration/targets/bigip_gtm_server/tasks/main.yaml

Issue- 2429 datacenter existence in check mode - resolved

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/issue_2424.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_snmp_community.py
test/integration/targets/bigip_snmp_community/tasks/issue-2424.yaml
test/integration/targets/bigip_snmp_community/tasks/main.yaml

Fixed Issue 2424 - allow v3 username with a number and special characters
