F5Networks/f5-ansible

library/bigip_software.py
tests/bigip_software.yaml

Add an option to bigip_software module to dynamically select one of existing inactive volumes (or create new one if no inactive volume in the system). The motivation of the change is to allow playbook to install software without specifying a volume name to which software is installed. If you have a playbook to install a new software into multiple bigip nodes at once, you may not be able to explicitly specify a volume name upfront. 
This module will give users an option to automatically select install volume from one of inactive volumes.
**Change**
- Add `reuse_inactive_volume` option
```
reuse_inactive_volume:
description:
- Automatically chooses the first inactive volume in alphanumeric order. If there
is no inactive volume, new volume with incremented volume name will be created.
For …
```

Add reuse_inactive_volume option to bigip_software module

---

library/bigip_device_dns.py

Quick add to correct the bigip_device_dns example included (it was a copy of the sysdb example).

Correct bigip_device_dns example

---

docs/modules/bigip_ssl_certificate_module.rst

- Documentation Report
bigip_ssl_certificate
```
ansible 2.2.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```
```
Python 2.7.12
f5-sdk 1.3.1
```
```
Sys::Version
Main Package
Product     BIG-IP
Version     12.1.1
Build       0.0.184
Edition     Final
Date        Thu Aug 11 17:09:01 PDT 2016
```
```
retry_files_enabled = False
host_key_checking=False
```
Alpine 3.4 (Docker Container)
The [documentation](https://f5-ansible.readthedocs.io/en/latest/modules/bigip_ssl_certificate_module.html) for the `bigip_ssl_certificate` module states that `f5-sdk >= 1.3.1` is one of the requirements, but it fails when using version 1.3.1, returning an error that complains about a missing object attribute `ssl_keys`:
```
class 'f5.bigip.tm.sys.file.File'>' …
```

bigip_ssl_certificate doc has wrong f5-sdk version dependency

---

library/bigip_pool2.py
test/integration/bigip_pool.yaml
test/unit/bigip/fixtures/load_ltm_pool.json
test/unit/bigip/fixtures/pool_members_subcollection.json
test/unit/bigip/test_bigip_pool.py

Problem:
bigip_pool lib needed an overhaul to use REST instead of SOAP
Analysis:
Reworked bigip_pool lib with the corresponding tests and
docs, to user REST and be in line with the new convention.
Created bigip_pool2.py so that the library
can gracefully replace bigip_pool.
Tests:
Unit
Functional

Fixes #133

---

library/bigip_pool2.py
test/unit/bigip/test_bigip_pool.py

Problem:
Not escaped '{' in the format string has caused ValueError exception. Full path to monitor was required to be provided.
Analysis:
Escaped '{' in the format string, all tests pass again. The full path to monitor is now being prepended automatically with the declared partition. 'Common' by default
Tests:
Unit
Functional

Fixes #145

---

library/bigip_device_connectivity.py

The function was retrieving the device group. Probably just leftover from using the device group module as a template is my guess.

Get the device, not the device group

---

library/bigip_configsync_actions.py

The overwrite_config parameter should add the force-full-load-push argument to the sync command unless I'm misunderstanding its purpose.
Need to wait for "Not All Devices Synced" state as well since the device group will typically go into this state immediately after starting the sync.

force-full-load-push and Not All Devices Synced state

---

test/integration/bigip_asm_policy.yaml
test/integration/bigip_command.yaml
test/integration/targets/bigip_asm_policy/tasks/issue-00406.yaml
test/integration/targets/bigip_command/tasks/main.yaml

Remove extra whitespace lines between tasks.
Use 2-space instead of 4-space indents in yaml files.

Formatting of asm_policy and command modules

---

test/integration/bigip_config.yaml
test/integration/bigip_configsync_action.yaml
test/integration/bigip_device_connectivity.yaml
test/integration/bigip_device_dns.yaml
test/integration/targets/bigip_config/tasks/main.yaml
test/integration/targets/bigip_configsync_action/tasks/main.yaml
test/integration/targets/bigip_configsync_action/tasks/setup.yaml
test/integration/targets/bigip_configsync_action/tasks/teardown.yaml
test/integration/targets/bigip_configsync_action/tasks/test-device-to-group.yaml
test/integration/targets/bigip_configsync_action/tasks/test-pull-recent-device.yaml
test/integration/targets/bigip_device_dns/tasks/main.yaml

Formatting and standards updates to config, configsync_action, device_connectivity, and device_dns modules.
- Decreased indents from 4 to 2 spaces
- Replaced '- include: *.yaml' with '-import_tasks: *.yaml'
- Replaced 'with_items:' with 'loop:'

Bugfix.formatting and standards

---

test/integration/bigip_device_trust.yaml
test/integration/bigip_dns_record.yaml
test/integration/bigip_dns_record_facts.yaml
test/integration/bigip_dns_zone.yaml
test/integration/bigip_drop_connection.yaml
test/integration/targets/bigip_device_trust/tasks/main.yaml
test/integration/targets/bigip_dns_zone/tasks/main.yaml

Updated device_trust, dns_record, dns_record_facts, dns_zone, and drop_connection modules to consistently use 2-space indents.

Updated 4-space indents to 2-space indents.

---

test/integration/bigip_gtm_server.yaml
test/integration/bigip_gtm_virtual_server.yaml
test/integration/bigip_gtm_wide_ip.yaml
test/integration/targets/bigip_gtm_server/tasks/main.yaml
test/integration/targets/bigip_gtm_virtual_server/tasks/main.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/main.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/type-a-gtm-wideip.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/type-aaaa-gtm-wideip.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/type-cname-gtm-wideip.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/type-mx-gtm-wideip.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/type-naptr-gtm-wideip.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/type-srv-gtm-wideip.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/typed-gtm-wideip.yaml

Updates to gtm_server, gtm_virtual_server, and gtm_wide_ip.
Consistent 2-space indents.
Replace "include *.yaml" with "import_tasks *.yaml"
Replace "with_items:" with "loop:"

More standards and formatting updates in gtm modules

---

test/integration/bigip_hostname.yaml
test/integration/bigip_irule.yaml
test/integration/bigip_license.yaml
test/integration/targets/bigip_hostname/tasks/main.yaml
test/integration/targets/bigip_irule/tasks/issue-00042.yaml
test/integration/targets/bigip_irule/tasks/issue-00316.yaml
test/integration/targets/bigip_irule/tasks/main.yaml
test/integration/targets/bigip_irule/tasks/setup.yaml
test/integration/targets/bigip_irule/tasks/teardown.yaml
test/integration/targets/bigip_license/tasks/main.yaml

2-space indents.
Replace "include: *.yaml" with "import_tasks: *.yaml"

Standards in hostname, irule, and license modules.

---

test/integration/bigip_monitor_http.yaml
test/integration/bigip_monitor_https.yaml
test/integration/bigip_monitor_snmp_dca.yaml
test/integration/bigip_monitor_tcp.yaml
test/integration/bigip_monitor_tcp_echo.yaml
test/integration/bigip_monitor_tcp_half_open.yaml
test/integration/targets/bigip_monitor_http/tasks/main.yaml
test/integration/targets/bigip_monitor_https/tasks/main.yaml
test/integration/targets/bigip_monitor_snmp_dca/tasks/main.yaml
test/integration/targets/bigip_monitor_tcp/tasks/legacy_tcp_echo.yaml
test/integration/targets/bigip_monitor_tcp/tasks/legacy_tcp_half_open.yaml
test/integration/targets/bigip_monitor_tcp/tasks/main.yaml
test/integration/targets/bigip_monitor_tcp_echo/tasks/main.yaml
test/integration/targets/bigip_monitor_tcp_half_open/tasks/main.yaml

Standardize on 2-space indents.
Replace "include: *.yaml" with "import_tasks: *.yaml"

Formatting and standards updates to all monitor modules.

---

test/integration/bigip_node.yaml
test/integration/bigip_partition.yaml
test/integration/bigip_policy.yaml
test/integration/bigip_policy_rule.yaml
test/integration/targets/bigip_node/defaults/main.yaml
test/integration/targets/bigip_node/tasks/node-by-address-ipv4.yaml
test/integration/targets/bigip_node/tasks/node-by-address-ipv6.yaml
test/integration/targets/bigip_node/tasks/node-by-fqdn.yaml
test/integration/targets/bigip_node/tasks/node-monitors.yaml
test/integration/targets/bigip_node/tasks/status-disabled.yaml
test/integration/targets/bigip_node/tasks/status-enabled.yaml
test/integration/targets/bigip_node/tasks/status-offline.yaml
test/integration/targets/bigip_node/tasks/status-present.yaml
test/integration/targets/bigip_node/tasks/statuses.yaml
test/integration/targets/bigip_node/vars/node-monitors.yaml
test/integration/targets/bigip_partition/tasks/main.yaml
test/integration/targets/bigip_partition/tasks/setup.yaml
test/integration/targets/bigip_partition/tasks/teardown.yaml
test/integration/targets/bigip_policy/tasks/main-draft.yaml
test/integration/targets/bigip_policy_rule/tasks/teardown.yaml

- Standardize on 2-space indents
- Replace "with_items:" with "loop:"
- Replace "include: *.yaml" with "import_tasks: *.yaml"

Applying standards to node, partition, policy, and policy_rule modules.

---

test/integration/bigip_snat_pool.yaml
test/integration/bigip_snmp.yaml
test/integration/bigip_snmp_community.yaml
test/integration/bigip_snmp_trap.yaml
test/integration/bigip_snmp_user.yaml
test/integration/targets/bigip_snat_pool/defaults/main.yaml
test/integration/targets/bigip_snat_pool/tasks/main.yaml
test/integration/targets/bigip_snmp/tasks/main.yaml
test/integration/targets/bigip_snmp_trap/tasks/main.yaml
test/integration/targets/bigip_snmp_trap/tasks/post-v12.yaml
test/integration/targets/bigip_snmp_trap/tasks/v12.0.0.yaml

- 2-space indenting
- replace 'include: *.yaml' with 'import_tasks: *.yaml'

Formatting and standards for snat_pool and snmp-related modules.

---

test/integration/bigip_software.yaml
test/integration/bigip_software_facts.yaml
test/integration/bigip_software_update.yaml
test/integration/targets/bigip_software/tasks/local.yaml
test/integration/targets/bigip_software/tasks/main.yaml
test/integration/targets/bigip_software/tasks/remote.yaml
test/integration/targets/bigip_software/tasks/setup.yaml
test/integration/targets/bigip_software_facts/tasks/main.yaml

- Standardize on 2-space indents
- Replace any 'include: *.yaml' with 'import_tasks: *.yaml'

Standards and formatting for integration tests in bigip_software_* modules.

---

test/integration/bigip_ucs.yaml
test/integration/bigip_ucs_fetch.yaml
test/integration/bigip_user.yaml
test/integration/bigip_user_facts.yaml
test/integration/targets/bigip_ucs/tasks/main.yaml
test/integration/targets/bigip_ucs/tasks/setup.yaml
test/integration/targets/bigip_ucs_fetch/tasks/main.yaml
test/integration/targets/bigip_user/defaults/main.yaml
test/integration/targets/bigip_user/tasks/issue-00113.yaml
test/integration/targets/bigip_user/tasks/issue-00276.yaml
test/integration/targets/bigip_user/tasks/issue-00310.yaml
test/integration/targets/bigip_user/tasks/main.yaml
test/integration/targets/bigip_user/tasks/setup.yaml
test/integration/targets/bigip_user/tasks/teardown.yaml
test/integration/targets/bigip_user/tasks/test-post-version-12-specific.yaml

- 2-space indenting
- replace 'include: *.yaml' with 'import_tasks: *.yaml'
- replace 'with_items:' with 'loop:'

Standards and formatting for integrated tests in bigip_ucs* and bigip_user* modules.

---

test/integration/bigip_vlan.yaml
test/integration/bigiq_license_pool.yaml
test/integration/bigiq_license_pool_member.yaml
test/integration/f5_support_upload.yaml
test/integration/targets/bigip_view/tasks/main.yaml
test/integration/targets/bigip_vlan/defaults/main.yaml
test/integration/targets/bigip_vlan/tasks/main.yaml
test/integration/targets/bigip_vlan/tasks/setup.yaml
test/integration/targets/bigip_wait/tasks/main.yaml
test/integration/targets/bigip_wait/tasks/teardown.yaml

Updates to integration tests for bigip_view, bigip_vlan, bigip_wait, bigiq_license_pool,  bigiq_license_pool_member,  and f5_support_upload modules.  The view and vlan modules were previously updated but grep and random inspection revealed needed updates that were previously missed.
- Standardize on 2-space indents
- Replace 'include: *.yaml' with 'import_tasks: *.yaml'
- Replace 'with_items:' with 'loop:'

Continuuing standards and formatting updates to integration tests.

---

test/integration/targets/bigip_profile_client_ssl/tasks/issue-00398.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/main.yaml
test/integration/targets/bigip_profile_client_ssl/tasks/test-cert-key-chain.yaml

1. Issue-00398 test created cert/key but did not remove at end of test.
2. main.yaml imported test-cert-key-chain.yaml in the middle of another test.  moved to after current test
3. test-cert-key-chain did not remove profile at end of test.  Removed profile with idempotent checks and assertions.

Fixed issues in bigip_profile_client_ssl module integration tests.

---

test/integration/targets/bigip_virtual_server/defaults/main.yaml
test/integration/targets/bigip_virtual_server/tasks/main.yaml
test/integration/targets/bigip_virtual_server/tasks/setup.yaml

The bigip_virtual_server integration test that sets a collection of profiles on a virtual was failing on 12.0 because the ssh profile did not exist.  Verified in dev central that it probably did not exist until 12.1.  Created a separate collection of profiles just for 12.0.

The /Common/ssh profile did not exist in 12.0.

---

test/integration/targets/bigip_virtual_server/tasks/main.yaml

I went through the bigip_virtual_server module integration tests to discover there aren't any tasks that will disable a virtual server so I added one and discovered that it doesn't work.  Will open a matching issue.

Add change state to disabled test for bigip_virtual_server.

---

test/integration/targets/bigip_software_update/tasks/main.yaml
test/integration/targets/bigip_software_update/tasks/setup.yaml

Tweaking integration test to skip some steps on 12.0.

The auto phone home parameter did not exist in BIGIP 12.0.

---

README.rst
docs/development/ssh-functionality-for-modules.rst

The edits to ssh-functionality-for-modules was intended to address GitHub Issue 503. Please review and make sure I haven't made anything technically inaccurate.
The edits to readme were to standardize link format and add group email address.

edited readme and ssh-functionality to try to standardize

---

library/modules/bigip_static_route.py

These changes allow for the 'partition' parameter which cannot be used as of Ansible version 2.5.

Add partition parameter to bigip_static_route

---

library/modules/bigip_asm_policy.py
test/integration/targets/bigip_asm_policy/tasks/issue-00406.yaml
test/integration/targets/bigip_asm_policy/tasks/issue-00595.yaml
test/integration/targets/bigip_asm_policy/tasks/main.yaml
test/integration/targets/bigip_asm_policy/tasks/setup.yaml

I had to gut it good due to a bug in import-policy task endpoint. This works on v13 and v12 now

removing SDK from asm_policy

---

library/modules/bigip_snat_pool.py
test/integration/targets/bigip_snat_pool/tasks/issue-01284.yaml
test/integration/targets/bigip_snat_pool/tasks/main.yaml
test/integration/targets/bigip_snat_pool/vars/issue-01284.yaml
test/units/modules/network/f5/test_bigip_snat_pool.py

Testing ran - 
```
root@ubuntu-ansible-python3:~/f5-ansible/test/integration# ansible-playbook -i inventory/hosts bigip_snat_pool.yaml -vvv --step
ansible-playbook 2.8.0
config file = /root/nitin_ansible.cfg
configured module search path = ['/root/f5-ansible/library/modules']
ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
executable location = /usr/local/bin/ansible-playbook
python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
Using /root/nitin_ansible.cfg as config file
[...]
statically imported: /root/f5-ansible/test/integration/targets/bigip_snat_pool/tasks/issue-01284.yaml
PLAYBOOK: bigip_snat_pool.yaml ***************************************************************************************************************************************** …
```

Adding description to SNAT pool

---

test/integration/targets/bigip_vcmp_guest/tasks/issue-00798.yaml
test/integration/targets/bigip_vcmp_guest/tasks/issue-00802.yaml
test/integration/targets/bigip_vcmp_guest/vars/issue-00798.yaml
test/integration/targets/bigip_vcmp_guest/vars/issue-00802.yaml

I forgot to send a pull request. This is a small fix to make sure that the issues do not use the default guest name 'guest1' when running in a sequence with the main integration test.

fixing guest names for vCMP issues

---

library/module_utils/network/f5/icontrol.py

fixes #1344
[StringIO.StringIO()](https://docs.python.org/2/library/stringio.html)(py2x) vs [io.StringIO()](https://docs.python.org/3/library/io.html)(py3x)
Bigip_data_group is using io module for StringIO buffer and icontrol.py was using module StringIO for StringIO buffer if present. If not present use io module which was the issue when using 2.7 since module StringIO is present in python pre 2.7.
Modified iControl to try io module first as it was introduced in 2.6 and try StringIO module on exception.

issue 1344

---

library/module_utils/network/f5/icontrol.py
library/modules/bigip_data_group.py

fixes #1344 
StringIO.StringIO()(py2x) vs io.StringIO()(py3x)
Modified bigip_data_group to first try to import StringIO (2.7) and if fails use io.StringIO (2.6+). This mirrors how icontrol.py is importing string buffer modules.
[test results.zip](https://github.com/F5Networks/f5-ansible/files/3427788/test.results.zip)

fix issue 1344

---

library/module_utils/network/f5/common.py
test/units/module_utils/network/f5/test_common.py

Updating transform_name util to escape route domain in pool names, nodes, etc.
Does NOT escape the same for partition name.
Proof of unit test passing - 
```
root@ubuntu-ansible-python2-7:~/f5-ansible# python -m pytest test/units/module_utils/network/f5/
============================================================================================ test session starts ============================================================================================
platform linux2 -- Python 2.7.5, pytest-4.6.4, py-1.8.0, pluggy-0.12.0
rootdir: /root/f5-ansible
collected 9 items
test/units/module_utils/network/f5/test_common.py .........                                                                                                                                           [100%] …
```

updating transform_name to allow for route domain; fixes #1401

---

library/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/defaults/main.yaml
test/integration/targets/bigip_device_info/tasks/issue-01364.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

I've left out the encrypted password as it doesn't make sense to include that information in the response. Primary use of bigip_device_info -> users  is to allow customers to track the users that exist.

Fixes #1364

---

library/modules/bigip_monitor_ldap.py
test/integration/targets/bigip_monitor_ldap/tasks/issue-01353.yaml
test/integration/targets/bigip_monitor_ldap/tasks/main.yaml

fixes #1353 
- added task to integration test which asserts username is set
- added task to integration test which asserts password is set
[unit_01353.log](https://github.com/F5Networks/f5-ansible/files/3469899/unit_01353.log)
[int_01353.log](https://github.com/F5Networks/f5-ansible/files/3469900/int_01353.log)

fixes 01353

---

library/modules/bigip_gtm_wide_ip.py
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/issue-persistence.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/main.yaml
test/integration/targets/bigip_gtm_wide_ip/vars/issue-persistence.yaml

Adds missing persistence and related persist_cidr_ipv4, persist_cidr_ipv6, and persistence_ttl options to the wide_ip

Add persistence enable-disable to wide_ip

---

library/modules/bigip_profile_persistence_src_addr.py
test/integration/targets/bigip_profile_persistence_src_addr/tasks/issue-01551.yaml
test/integration/targets/bigip_profile_persistence_src_addr/tasks/main.yaml

The webGUi allows the user to input a prefix length number (0-32 for IPv4 and 0-128 for IPv6) but it seems that the API expects it to be a proper mask, because there is no additional field for IP version in the API.
Thus, I've made is so that the mask will be a full mask of type '255.255.255.255' or 'ffff::'

Fixes #1551

---

library/modules/bigip_data_group.py
test/integration/targets/bigip_data_group/tasks/issue-01587.yaml
test/integration/targets/bigip_data_group/tasks/main.yaml

I looked far and wide for a solution such that we could use python's decode functionality, but we're handicapped by the fact that BIG-IP adds two backslashes instead of one. This is necessary to display the config in tmsh.
So, the safest way to do this is to do a regex replace.
Currently, only dealing with the situation where the string '\\?' shows up. If in the future, we find more corner cases, we should convert this into a function, and then perhaps a library function.

Fixes #1587

---

library/modules/bigip_gtm_wide_ip.py
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/issue-01597.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/main.yaml
test/integration/targets/bigip_gtm_wide_ip/tasks/environment/type-a-gtm-wideip.yaml
test/units/modules/network/f5/fixtures/load_gtm_wide_ip_with_pools.json
test/units/modules/network/f5/test_bigip_gtm_wide_ip.py

This change allows specifying order on pools used for bigip_gtm_wide_ip module. 
-  Update bigip_gtm_wide_ip module to allow setting order value for each pool
-  Update unit tests to test new property
- Update integration tests

FMFA-413: Update bigip_gtm_wide_ip module to allow passing pools order

---

library/modules/bigip_policy_rule.py
test/integration/targets/bigip_policy_rule/tasks/issue-01546.yaml
test/integration/targets/bigip_policy_rule/tasks/issue-01678.yaml
test/integration/targets/bigip_policy_rule/tasks/main.yaml

This change is intended to enable support for set_variable action for bigip_pool_rule module. 
Related to the following issue: https://github.com/F5Networks/f5-ansible/issues/1678
- Update bigip_module_rule module to allow setting set_variable action
- Add integration tests for new action
```
PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************
bigip_v12                  : ok=206  changed=76   unreachable=0    failed=0    skipped=8    rescued=0    ignored=2   
bigip_v13                  : ok=212  changed=79   unreachable=0    failed=0    skipped=2    rescued=0    ignored=2 …
```

FMFA-467: Enable support for set_variable action on bigip_pool_rule module

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_policy_fetch.py

- change from asm rest endpoint to software-image-downloads endpoint
- replace `download_file` with `download_asm_file` (import from` ..module_utils.icontrol`) to adopt to new endpoint
- add `_move_file_to_download` to `create_on_device` function (similar to `bigip_asm_policy_fetch` approach)
- update paths as relevant
addresses #1780
status: works for me

fix bigip_apm_policy_fetch issue

---

ansible_collections/f5networks/f5_modules/plugins/action/bigip.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
test/integration/targets/bigip_command/tasks/provider-cli/issue-01728.yaml
test/integration/targets/bigip_command/tasks/provider-cli/main.yaml

Fixes for bugs found with Wojciech and trying warnings for messages
Not sure how to display a warning/error without raising an error.
I tried display.warning, but that. seems to only work in Ansible plugins, not modules.
Currently, the solution is to use F5ModuleError to simplify the error displayed, and to specify that the wait_for condition has failed.

Fixes #1728

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/1903-fix-mgmt-route-not-idempotent.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_management_route.py
test/integration/targets/bigip_management_route/defaults/main.yaml
test/integration/targets/bigip_management_route/tasks/issue-01903.yaml
test/integration/targets/bigip_management_route/tasks/main.yaml

Fixes the issue of mgmt route creation not idempotent in the case of route name containing /subnet_mask (like /32)

Fixes #1903

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-snat-pool-device-info.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py

ok: [bigip1] => {
"ansible_facts": {
"ansible_net_queried": true,
"ansible_net_virtual_servers": [
{
"auto_lasthop": "default",
"availability_status": "unknown",
"client_side_bits_in": 0,
"client_side_bits_out": 0,
"client_side_current_connections": 0,
"client_side_evicted_connections": 0,
"client_side_max_connections": 0,
"client_side_pkts_in": 0,
"client_side_pkts_out": 0,
"client_side_slow_killed": 0,
"client_side_total_connections": 0,
"cmp_enabled": "yes",
"cmp_mode": "all-cpus",
"connection_limit": 0,
"connection_mirror_enabled": "no",
"cpu_usage_ratio_last_1_min": 0,
"cpu_usage_ratio_last_5_min": 0,
"cpu_usage_ratio_last_5_sec": 0,
"current_syn_cache": 0,
"destination": "/Common/10.0.0.1:80",
"destination_address": "10.0.0.1",
"destination_port": 80,
"enabled": "yes", …

Fix snat pool issue in device info module

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/syslog_include_support_escaped_quotes.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_syslog.py
test/integration/targets/bigip_device_syslog/tasks/include.yaml

This change is to allow escaped " as they are, and only replace unescaped " with '.
```
ansible-playbook -i inventory/hosts ../f5-ansible/test/integration/bigip_device_syslog.yaml -t "include"
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: file /Users/r.upadhyay/Documents/github/f5_ansible_dev_workspace/f5-ansible/test/integration/targets/bigip_device_syslog/tasks/setup.yaml is empty and had no tasks to
include
[WARNING]: file /Users/r.upadhyay/Documents/github/f5_ansible_dev_workspace/f5-ansible/test/integration/targets/bigip_device_syslog/tasks/teardown.yaml is empty and had no tasks
to include
PLAY [Metadata of bigip_device_syslog] ********************************************************************************************** …
```

Replace only unescaped " with ' for include value in bigip_device_syslog

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/bugfix-bigip-command.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
test/integration/targets/bigip_command/tasks/environment/handle-pipe.yaml
test/integration/targets/bigip_command/tasks/environment/main.yaml

```
(venv-3.9) ➜ ansible-playbook ../f5-ansible/test/integration/bigip_command.yaml -t "environment" --step
PLAY [Metadata of bigip_command] *********************************************************************************************************************************
PLAY [Test the bigip_command module - Environment] ***************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: *******************************************************************************************************
TASK [Gathering Facts] *********************************************************************************************************************** …
```

fixed bug in bigip_command module related to interpretation of pipe

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_remote_role.py

group_name is not supported.
remote_access is a yes or a no.

Fix example on bigip_remote_role

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/add-parameter-aliases-bigip-pool.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py
test/integration/targets/bigip_pool/tasks/issue-02222.yaml
test/integration/targets/bigip_pool/tasks/main.yaml

This is to close #2222 . I have added aliases for `monitor_type` and `quorum` to make them look similar to availability requirements parameter in bigip_pool_member.
```
ansible-playbook ../f5-ansible/test/integration/bigip_pool.yaml -t "issue-02222"
PLAY [Metadata of bigip_pool] ****************************************************************************************************************************************************
PLAY [Test the bigip_pool module] ************************************************************************************************************************************************
TASK [bigip_pool : Issue 02222 - Create a pool with availability requirements] ***************************************************************************************************
changed: …
```

Added aliases to params related to availability requirement

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/sr-fix-image-upload-bug.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_image.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_software_image.py
test/integration/targets/bigip_software_image/tasks/main.yaml
test/integration/targets/bigip_software_image/tasks/sr-1-8581427611.yaml

```
root@ubuntu:~/github/V1# ansible-playbook ../f5-ansible/test/integration/bigip_software_image.yaml -t "sr-1-8581427611" --step
[WARNING]: file /root/github/f5-ansible/test/integration/targets/bigip_software_image/tasks/teardown.yaml is empty and had no tasks to include
PLAY [Metadata of bigip_software_image] ******************************************************************************************************************************************
PLAY [Test the bigip_software_image module] **************************************************************************************************************************************
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: y
Perform task: TASK: Gathering Facts (N)o/(y)es/(c)ontinue: …
```

Fixed permission and ownership for uploaded image file

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/add-license-option-bigip-device-info.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
test/integration/targets/bigip_device_info/tasks/issue-license-info.yaml
test/integration/targets/bigip_device_info/tasks/main.yaml

Added option to bigip_device_info to gather info for the license
```
ansible-playbook ../../f5-ansible/test/integration/bigip_device_info.yaml -t "issue-license"
PLAY [Metadata of bigip_device_info] *********************************************************************************************************************************************
PLAY [Test the bigip_device_info module] *****************************************************************************************************************************************
ok: [bigip16]
TASK [bigip_device_info : Gather License info] …
```

Added option for license in bigip_device_info

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/fix-infinite-loop-device-license.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/common.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_license.py
test/integration/targets/bigip_device_license/tasks/issue-02275.yaml
test/integration/targets/bigip_device_license/tasks/main.yaml

Fixes #2275
```
❯ ansible-playbook ../../f5-ansible/test/integration/bigip_device_license.yaml -t "issue-02275"
[WARNING]: Found both group and host with same name: f5os
[WARNING]: file /Users/r.upadhyay/Documents/github/f5_ansible/f5-ansible/test/integration/targets/bigip_device_license/tasks/teardown.yaml is empty and had no tasks to include
PLAY [Metadata of bigip_device_license] ******************************************************************************************************************************************
PLAY [Test the bigip_device_license module] **************************************************************************************************************************************
TASK [Gathering Facts] ************************************************************************* …
```

Add fix for bug causing infinite loop in bigip_device_license

---

README.rst

Closes #2295 . Added a note in the README regarding fixing ssh connection issue caused by libssh when using bigip_device_certificate module

Added note about ssh_type related to bigip_device_certificate

---

ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py

Added a not e to module documentation regarding setting ssh type to paramiko when using bigip_device_certificate.

Added a note to bigip_device_certificate regarding ssh type

---

README.rst
ansible_collections/f5networks/f5_modules/changelogs/fragments/bigip-command-long-running-cmd-fix.yaml
ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
test/integration/targets/bigip_command/tasks/provider-rest/main.yaml
test/integration/targets/bigip_command/tasks/provider-rest/sleep.yaml
test/integration/targets/bigip_command/vars/issue-00843.yaml

```
ansible-playbook ../../f5-ansible/test/integration/bigip_command.yaml -t "provider" --start-at-task="sleep for 200 seconds" --step
PLAY [Metadata of bigip_command] *************************************************************************************************************************************************
PLAY [Test the bigip_command module - Environment] *******************************************************************************************************************************
PLAY [Test the bigip_command module - Provider-cli] ******************************************************************************************************************************
PLAY [Test the bigip_command module - Provider-rest] *************************************************************************** …
```

Added timeout fix for long running commands in bigip_command

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/error-handling-for-connection-error.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py
ansible_collections/f5networks/f5_modules/tests/unit/modules/network/f5/test_bigip_device_certificate.py

#2353 
```
test_bigip_device_certificate.py ....                                                                                                              [100%]
=================================================================== 4 passed in 0.19s ====================================================================
Name                                                                                                                  Stmts   Miss  Cover
-----------------------------------------------------------------------------------------------------------------------------------------
/Users/p.ramani/F5/f5-ansible/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/config.py       326    258    21%
/Users/p.ramani/F5/f5-ansible/ansible_collections/ansible/netcommo …
```

Issue-2353 : Error Handling for Connection Error while executing command

---

ansible_collections/f5networks/f5_modules/changelogs/fragments/bigip-ucs-restore-fix.yaml
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs.py
requirements.txt

Integration test results:
```
(.venv) ➜  f5-ansible git:(devel_ucs_fix) ✗ ansible-playbook -i ~/devsettings/inventory/bigip_ucs /Users/r.chinthalapalli/PycharmProjects/ansible/f5-ansible/test/integration/bigip_ucs.yaml  -vvvv
ansible-playbook [core 2.17.2]
config file = /Users/r.chinthalapalli/PycharmProjects/ansible/f5-ansible/ansible.cfg
configured module search path = ['/Users/r.chinthalapalli/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /Users/r.chinthalapalli/PycharmProjects/ansible/f5-ansible/.venv/lib/python3.12/site-packages/ansible
ansible collection location = /Users/r.chinthalapalli/PycharmProjects/ansible/f5-ansible
executable location = /Users/r.chinthalapalli/PycharmProjects/ansible/f5-ansible/.venv/bin/ansible-playbook …
```

adding bigip_ucs module fix
